/* ==================================================================
   The Weekly Stampede  —  scenes.js
   Cinematic parallax backdrops, one per news region.

   Plain browser JS. No modules, no build step, no external assets.
   Exposes exactly two globals:
     SCENES              { region: { name, badge, tint, sky:[stops] } }
     sceneHTML(region)   -> HTML string: .sky + .layer far/mid/near

   THE LOOK — a gold trading floor at the end of the day
     - ONE low sun per scene, always right of x=800, always near the
       horizon. It is the only real light: everything in front of it
       is a backlit silhouette, rim-lit on the side facing it.
     - a CANDLESTICK WALL projected on the sky behind the skyline,
       generated by a seeded random walk so it reads as price action
     - a polished FLOOR below the horizon: receding grid + the sun
       smeared down it
     - atmospheric perspective: layer colours are MIXED toward the sky
       colour by distance, so `far` sits closest to the sky, `mid`
       clearly darker, `near` almost black
     - each layer ends with a haze gradient rising off the horizon, so
       building bases dissolve instead of sitting on a hard line
     - massing is generated: setbacks, varied crowns, roof plant,
       antennae, clumped/overlapping spacing, per-building value jitter

   THE LEFT SIDE IS RESERVED. The story column sits over the left 45%
   in warm bone (#EDE6D6). Every scene therefore keeps its sun and its
   bright core to the RIGHT, fades the candle wall out toward the
   left, and lays a horizontal shade gradient over the left of both
   the sky and the far layer. Copy legibility beats scenery.

   All geometry is DETERMINISTIC (mulberry32 — never Math.random).
   Horizon is y=760 in the 1600x900 viewBox; the page paints its own
   ground band below, so no detail is drawn under it. Every gradient
   and clip id is region-prefixed so all ten can coexist in the DOM.
   ================================================================== */
(function (root) {
'use strict';

/* ==================================================================
   1. Toolkit — PRNG, colour maths, primitive emitters
   ================================================================== */
var G = 760;                            // the horizon line
var BONE = '#EDE6D6';
var AMBER = '#F5B843';

function R(seed) {                      // mulberry32, seeded, repeatable
  var t = seed >>> 0;
  return function () {
    t = (t + 0x6D2B79F5) >>> 0;
    var x = Math.imul(t ^ (t >>> 15), 1 | t);
    x = (x + Math.imul(x ^ (x >>> 7), 61 | x)) ^ x;
    return ((x ^ (x >>> 14)) >>> 0) / 4294967296;
  };
}
function loop(n, f) { var s = '', i; for (i = 0; i < n; i++) s += f(i); return s; }
function nn(v) { return Math.round(v * 10) / 10; }

function hx(h) { h = h.replace('#', ''); return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)]; }
function rgb(a) { return '#' + a.map(function (v) { v = Math.max(0, Math.min(255, Math.round(v))); return (v < 16 ? '0' : '') + v.toString(16); }).join(''); }
function mix(a, b, t) { var A = hx(a), B = hx(b); return rgb([A[0] + (B[0] - A[0]) * t, A[1] + (B[1] - A[1]) * t, A[2] + (B[2] - A[2]) * t]); }

function rect(x, y, w, h, f, ex) { return '<rect x="' + nn(x) + '" y="' + nn(y) + '" width="' + nn(w) + '" height="' + nn(h) + '" fill="' + f + '"' + (ex || '') + '/>'; }
function box(x, w, h, f, ex) { return rect(x, G - h, w, h, f, ex); }
function pathd(d, f, ex) { return '<path d="' + d + '" fill="' + f + '"' + (ex || '') + '/>'; }
function circ(cx, cy, r, f, ex) { return '<circle cx="' + nn(cx) + '" cy="' + nn(cy) + '" r="' + nn(r) + '" fill="' + f + '"' + (ex || '') + '/>'; }
function elli(cx, cy, rx, ry, f, ex) { return '<ellipse cx="' + nn(cx) + '" cy="' + nn(cy) + '" rx="' + nn(rx) + '" ry="' + nn(ry) + '" fill="' + f + '"' + (ex || '') + '/>'; }
function poly(p, f, ex) { return '<polygon points="' + p + '" fill="' + f + '"' + (ex || '') + '/>'; }
function pts(a) { var o = [], i; for (i = 0; i < a.length; i += 2) o.push(nn(a[i]) + ',' + nn(a[i + 1])); return o.join(' '); }
function ln(x1, y1, x2, y2, c, w, o) { return '<line x1="' + nn(x1) + '" y1="' + nn(y1) + '" x2="' + nn(x2) + '" y2="' + nn(y2) + '" stroke="' + c + '" stroke-width="' + w + '" opacity="' + o + '"/>'; }
function strk(d, c, w, o, cap) { return '<path d="' + d + '" fill="none" stroke="' + c + '" stroke-width="' + w + '" opacity="' + (o === undefined ? 1 : o) + '"' + (cap ? ' stroke-linecap="round"' : '') + '/>'; }

/* symmetric silhouette from a half-width function of t (0 = ground) */
function profile(cx, h, halfW, n, f, ex) {
  var L = [], Rt = [], i, t;
  for (i = 0; i <= n; i++) { t = i / n; L.push(cx - halfW(t), G - h * t); }
  for (i = n; i >= 0; i--) { t = i / n; Rt.push(cx + halfW(t), G - h * t); }
  var p = pts(L.concat(Rt));
  return { pts: p, svg: poly(p, f, ex) };
}

/* ==================================================================
   2. Atmosphere — palette, haze, bloom
   ================================================================== */
/* Distance wash. Against a bright gold sky the buildings are read as
   SILHOUETTES, so the far layer is pulled toward the sky much less
   than it would be in a front-lit scene — enough for haze, not enough
   to lose the outline. The rims are pushed hard the other way: they
   are the sun catching an edge, so they run near the sun's own value. */
function palette(c) {
  var far = mix(c.ink, c.hz, 0.44), mid = mix(c.ink, c.hz, 0.11), near = mix(mix(c.ink, '#000000', 0.55), c.hz, 0.04);
  return {
    far:  { fill: far,  rim: mix(far, c.sun, 0.58), haze: c.hz, sunX: c.sunX, win: true, wd: 0.26, wop: 0.10, wband: 0.12, gx: 13, gy: 17, cw: 4, ch: 5, rimOp: c.rimOp * 0.55, dipX: c.sunX, dipW: 330, dipK: 0.20 },
    mid:  { fill: mid,  rim: mix(mid, c.sun, 0.66), haze: c.hz, sunX: c.sunX, win: true, wd: 0.44, wop: 0.32, wband: 0.22, gx: 17, gy: 23, cw: 6, ch: 8, rimOp: c.rimOp, dipX: c.sunX, dipW: 290, dipK: 0.26 },
    near: { fill: near, rim: mix(near, c.sun, 0.46), haze: c.hz, sunX: c.sunX, win: false, rimOp: c.rimOp * 0.8 },
    dist: { fill: mix(far, c.hz, 0.44), rim: mix(far, c.sun, 0.4), haze: c.hz, sunX: c.sunX, win: false, rimOp: c.rimOp * 0.3, dipX: c.sunX, dipW: 360, dipK: 0.30 },
    /* candle wall inks: a rising mark is bright gold, a falling one burnt amber */
    cUp: mix(c.hz, c.sun, 0.60), cDn: mix(c.hz, '#7C3410', 0.46)
  };
}
/* A copy of a layer config pushed further toward the sky. `palette`
   gives four fixed distances, which is enough when a scene is one city;
   it is not enough when the subject IS the distance between several of
   them. Value is the only cue the eye has here — everything is a flat
   silhouette — so each extra cluster needs its own wash rather than
   being drawn in a neighbour's ink and hoping the spacing carries it. */
function wash(base, t, c) {
  var o = {}, k;
  for (k in base) if (Object.prototype.hasOwnProperty.call(base, k)) o[k] = base[k];
  o.fill = mix(base.fill, c.hz, t);
  o.rim = mix(base.rim, c.hz, t * 0.55);
  o.rimOp = base.rimOp * (1 - t * 0.55);
  if (base.wop) o.wop = base.wop * (1 - t * 0.78);
  return o;
}
/* haze rising off the horizon; drawn last inside a layer */
function haze(id, colour, top, op) {
  return '<defs><linearGradient id="' + id + '" x1="0" y1="0" x2="0" y2="1">' +
    '<stop offset="0" stop-color="' + colour + '" stop-opacity="0"/>' +
    '<stop offset="0.5" stop-color="' + colour + '" stop-opacity="' + (op * 0.34).toFixed(3) + '"/>' +
    '<stop offset="1" stop-color="' + colour + '" stop-opacity="' + op + '"/></linearGradient></defs>' +
    rect(-140, top, 1880, G - top + 8, 'url(#' + id + ')');
}
function bloom(id, x, y, r, colour, op) {
  return '<defs><radialGradient id="' + id + '"><stop offset="0" stop-color="' + colour + '" stop-opacity="' + op + '"/>' +
    '<stop offset="0.45" stop-color="' + colour + '" stop-opacity="' + (op * 0.34).toFixed(3) + '"/>' +
    '<stop offset="1" stop-color="' + colour + '" stop-opacity="0"/></radialGradient></defs>' + circ(x, y, r, 'url(#' + id + ')');
}
/* soft stratus bars, kept low-contrast */
function clouds(seed, n, colour, y0, y1, op) {
  var r = R(seed), s = '', i, y;
  for (i = 0; i < n; i++) { y = y0 + r() * (y1 - y0); s += elli(-100 + r() * 1800, y, 220 + r() * 420, 9 + r() * 22, colour, ' opacity="' + (op * (0.4 + r() * 0.6)).toFixed(3) + '"'); }
  return s;
}
function stars(seed, n, ymax) {
  var r = R(seed), s = '', i, v;
  for (i = 0; i < n; i++) { v = r(); s += circ(r() * 1600, r() * (ymax || 500), v < 0.86 ? 0.9 : 1.7, BONE, ' opacity="' + (0.1 + v * 0.4).toFixed(2) + '"'); }
  return s;
}

/* ------------------------------------------------------------------
   The sun. Low, hot, and always right of x=800. A wide bloom, a low
   anamorphic streak lying along the horizon, a tight halo, then the
   disc itself. Two gradient ids per call, both caller-prefixed.
   ------------------------------------------------------------------ */
function sunCore(id, x, y, r0, core, glow, op) {
  return bloom(id + 'w', x, y, r0 * 8.4, glow, op * 0.52) +
    elli(x, y, r0 * 10.5, r0 * 1.6, 'url(#' + id + 'w)') +
    bloom(id + 't', x, y, r0 * 3.0, mix(glow, core, 0.55), op * 0.85) +
    circ(x, y, r0 * 1.55, core, ' opacity="' + (op * 0.32).toFixed(3) + '"') +
    circ(x, y, r0, core, ' opacity="' + Math.min(1, op * 1.7).toFixed(3) + '"');
}

/* ------------------------------------------------------------------
   The candlestick wall — rows of price action projected on the sky
   BEHIND the skyline. Each row is a seeded random walk: the open is
   the previous close, plus a drift, a volatility term and a little
   mean reversion so the series stays inside its band. Rows differ in
   pitch, band height and weight so the wall reads as depth, and every
   row is faded out toward the LEFT so the story column keeps its
   contrast. Atmosphere, not subject — nothing here goes above ~0.24.
   ------------------------------------------------------------------ */
var CANDLE_ROWS = [
  /*  y    band  pitch body wick  op    drift  vol   x0  */
  { y: 148, h: 104, p: 19, b: 6,  w: 0.9, o: 0.13, d:  0.20, v: 1.9, x: -150 },
  { y: 268, h: 178, p: 33, b: 12, w: 1.5, o: 0.20, d: -0.24, v: 2.6, x:  -70 },
  { y: 402, h: 116, p: 16, b: 5,  w: 0.8, o: 0.11, d:  0.14, v: 1.5, x: -160 },
  { y: 524, h: 198, p: 48, b: 18, w: 2.1, o: 0.23, d:  0.30, v: 3.4, x: -220 },
  { y: 646, h: 112, p: 25, b: 9,  w: 1.2, o: 0.15, d: -0.22, v: 2.1, x: -110 }
];
function candleWall(seed, up, dn, k) {
  var out = '', ri;
  for (ri = 0; ri < CANDLE_ROWS.length; ri++) {
    var C = CANDLE_ROWS[ri], r = R(seed + ri * 7919),
        n = Math.ceil((1780 - C.x) / C.p),
        O = [], K = [], H = [], L = [], p = 0, mn = 1e9, mx = -1e9,
        i, a, b, hi, lo, sc, mid = C.y + C.h / 2, s = '';
    for (i = 0; i < n; i++) {                                        // the walk
      a = p;
      b = a + C.d + (r() - 0.5) * 2 * C.v - a * 0.06;                // drift + vol + reversion
      hi = (a > b ? a : b) + r() * C.v * 0.8;
      lo = (a < b ? a : b) - r() * C.v * 0.8;
      O.push(a); K.push(b); H.push(hi); L.push(lo);
      if (lo < mn) mn = lo;
      if (hi > mx) mx = hi;
      p = b;
    }
    sc = C.h / Math.max(0.001, mx - mn);                             // fit the row to its band
    for (i = 0; i < n; i++) {                                        // the marks
      var x = C.x + i * C.p, fd = (x - 240) / 790;
      fd = 0.05 + 0.95 * (fd < 0 ? 0 : fd > 1 ? 1 : fd);             // left fade
      var col = K[i] >= O[i] ? up : dn, op = C.o * k * fd,
          yo = mid - (O[i] - mn) * sc, yk = mid - (K[i] - mn) * sc;
      if (op < 0.005) continue;
      s += ln(x + C.b / 2, mid - (H[i] - mn) * sc, x + C.b / 2, mid - (L[i] - mn) * sc, col, C.w, (op * 0.7).toFixed(3));
      s += rect(x, Math.min(yo, yk), C.b, Math.max(2, Math.abs(yk - yo)), col, ' opacity="' + op.toFixed(3) + '"');
    }
    s += ln(560, mid, 1740, mid, up, 0.8, (C.o * k * 0.34).toFixed(3));   // the row's scale line
    out += s;
  }
  return out;
}

/* ------------------------------------------------------------------
   The polished floor. The page paints its own ground band over the
   bottom 17% (viewBox y >= ~747) and that band is only half opaque at
   its top edge, so every mark is packed into y = 760..815 where it
   still shows: a receding grid converging on the sun, then the sun
   smeared down the slab in broken ripples.
   ------------------------------------------------------------------ */
function floorPlate(id, sunX, C, sun, seed) {
  var r = R(seed), s = rect(-140, G, 1880, 148, C.fill);
  s += loop(6, function (i) {                                        // horizontals, packed near the horizon
    var t = (i + 1) / 7;
    return ln(-140, G + 56 * t * t, 1740, G + 56 * t * t, C.rim, 0.9, (0.17 * (1 - t * 0.75)).toFixed(3));
  });
  s += loop(16, function (i) {                                       // verticals, to a vanishing point at the sun
    var x = -420 + i * 250;
    return ln(sunX + (x - sunX) * 0.07, G, x, G + 60, C.rim, 1, 0.075);
  });
  s += '<defs><radialGradient id="' + id + '">' +
    '<stop offset="0" stop-color="' + sun + '" stop-opacity="0.55"/>' +
    '<stop offset="0.5" stop-color="' + sun + '" stop-opacity="0.16"/>' +
    '<stop offset="1" stop-color="' + sun + '" stop-opacity="0"/></radialGradient></defs>';
  s += elli(sunX, G + 16, 64, 70, 'url(#' + id + ')') + elli(sunX, G + 4, 230, 20, 'url(#' + id + ')');
  s += loop(12, function (i) {                                       // broken ripples in the smear
    var w = (84 - i * 5) * (0.45 + r());
    return rect(sunX - w / 2 + (r() - 0.5) * 30, G + 2 + i * 4.3, w, 1.8, sun, ' opacity="' + (0.30 * (1 - i / 13)).toFixed(3) + '"');
  });
  return s + rect(-140, G - 1.5, 1880, 2.5, C.rim, ' opacity="0.15"');
}

/* ------------------------------------------------------------------
   Left-hand shade. The hard requirement: warm bone copy sits over the
   left 45% of the frame, so that side is sunk into shadow. Laid over
   the far layer (and again, as a second background, on the sky) after
   everything else in it has been drawn.
   ------------------------------------------------------------------ */
/* The rect spans x = -140..1740, so in bbox units the stops land at
   x = -140, 311, 687 and 1026: full shadow over the copy, fully
   released before the sun so the right of the frame stays hot gold. */
function shade(id, colour, a0) {
  a0 = a0 === undefined ? 0.68 : a0;
  return '<defs><linearGradient id="' + id + '" x1="0" y1="0" x2="1" y2="0">' +
    '<stop offset="0" stop-color="' + colour + '" stop-opacity="' + a0.toFixed(3) + '"/>' +
    '<stop offset="0.24" stop-color="' + colour + '" stop-opacity="' + (a0 * 0.78).toFixed(3) + '"/>' +
    '<stop offset="0.44" stop-color="' + colour + '" stop-opacity="' + (a0 * 0.36).toFixed(3) + '"/>' +
    '<stop offset="0.62" stop-color="' + colour + '" stop-opacity="0"/></linearGradient></defs>' +
    rect(-140, -80, 1880, 1010, 'url(#' + id + ')');
}

/* ==================================================================
   3. Massing — windows, towers, city bands, roof clutter
   ================================================================== */
/* Office light clusters: lit floors, lit blocks, denser lower down. */
function winGrid(x, y, w, h, seed, C) {
  var r = R(seed), gx = C.gx || 17, gy = C.gy || 23, cw = C.cw || 6, ch = C.ch || 8,
      cols = Math.floor((w - 10) / gx), rows = Math.floor((h - 14) / gy), s = '', i, j, k, run, p, op, x0, full;
  if (cols < 1 || rows < 1) return '';
  x0 = x + (w - ((cols - 1) * gx + cw)) / 2;
  for (j = 0; j < rows; j++) {
    p = C.wd * (0.22 + 0.78 * (rows < 2 ? 1 : j / (rows - 1)));      // denser toward the base
    full = r() < C.wband;                                            // whole floor lit
    i = 0;
    while (i < cols) {
      if (full || r() < p) {
        run = full ? cols - i : 1 + Math.floor(r() * 3.4);
        op = C.wop * (0.5 + r() * 0.65);
        for (k = 0; k < run && i < cols; k++, i++) s += rect(x0 + i * gx, y + 10 + j * gy, cw, ch, AMBER, ' opacity="' + op.toFixed(2) + '"');
      } else i += 1 + Math.floor(r() * 3);
    }
  }
  return s;
}
/* faint vertical piers — the Art-Deco / stone-tower read */
function piers(x, y, w, h, col, op) {
  var n = Math.max(3, Math.round(w / 15));
  return loop(n, function (i) { return rect(x + 5 + i * ((w - 10) / n), y + 5, 2.5, h - 8, col, ' opacity="' + (op || 0.14) + '"'); });
}
/* rooftop plant: cooling boxes, vents, a mast */
function roofPlant(x, y, w, seed, f, rim) {
  var r = R(seed), s = '';
  if (w > 40) s += rect(x + w * 0.16, y - 11 - r() * 8, w * 0.34, 20, f);
  if (w > 60 && r() < 0.7) s += rect(x + w * 0.62, y - 8, w * 0.2, 10, f);
  if (r() < 0.5) s += rect(x + w * 0.5, y - 34 - r() * 26, 2.5, 40, f) + circ(x + w * 0.5 + 1, y - 36 - r() * 26, 2, AMBER, ' opacity="0.55"');
  return s + rect(x, y - 3, w, 3.5, rim, ' opacity="0.28"');
}

/* One tower: stacked setbacks, crown, plant, rim light, windows. */
function tower(x, w, h, C, seed, o) {
  o = o || {};
  var r = R(seed), s = '', segs = [], i, sg, sh, lit, y = G, cw = w, cx = x + w / 2, left = h,
      n = o.setbacks !== undefined ? o.setbacks + 1 : (r() < 0.40 ? 2 : (r() < 0.62 ? 1 : 3)),
      f = mix(C.fill, C.haze, r() * 0.17);                            // per-building value jitter
  for (i = 0; i < n; i++) {
    sh = (i === n - 1) ? left : left * (0.42 + r() * 0.3);
    segs.push({ x: cx - cw / 2, w: cw, y: y - sh, h: sh });
    y -= sh; left -= sh; cw *= 0.64 + r() * 0.18; cx += (r() - 0.5) * w * 0.14;
  }
  for (i = 0; i < segs.length; i++) {
    sg = segs[i];
    s += rect(sg.x, sg.y, sg.w, sg.h, f);
    if (C.win) s += winGrid(sg.x, sg.y, sg.w, sg.h, seed + i * 97 + 11, C);
    if (o.piers) s += piers(sg.x, sg.y, sg.w, sg.h, C.rim, 0.13);
    lit = C.sunX > sg.x + sg.w / 2 ? 1 : -1;
    s += rect(lit > 0 ? sg.x + sg.w - 3 : sg.x, sg.y, 3, sg.h, C.rim, ' opacity="' + C.rimOp + '"');
    if (i < segs.length - 1) s += rect(sg.x, sg.y - 3, sg.w, 3.5, C.rim, ' opacity="' + (C.rimOp * 0.6).toFixed(2) + '"');
  }
  sg = segs[segs.length - 1];
  switch (o.crown || ['flat', 'mech', 'step', 'pitch', 'spire', 'flat', 'mech'][Math.floor(r() * 7)]) {
    case 'mech': s += rect(sg.x + sg.w * 0.18, sg.y - 18, sg.w * 0.44, 19, f) + rect(sg.x + sg.w * 0.68, sg.y - 11, sg.w * 0.2, 12, f); break;
    case 'step': s += rect(sg.x + sg.w * 0.1, sg.y - 15, sg.w * 0.8, 16, f) + rect(sg.x + sg.w * 0.28, sg.y - 28, sg.w * 0.44, 14, f); break;
    case 'pitch': s += poly(pts([sg.x - 4, sg.y + 1, sg.x + sg.w / 2, sg.y - sg.w * 0.46, sg.x + sg.w + 4, sg.y + 1]), f); break;
    case 'spire': s += rect(sg.x + sg.w / 2 - 2.5, sg.y - 70, 5, 72, f) + circ(sg.x + sg.w / 2, sg.y - 74, 3.2, AMBER, ' opacity="0.7"'); break;
  }
  return s + roofPlant(sg.x, sg.y, sg.w, seed + 5, f, C.rim);
}

/* A stretch of city: clumped, overlapping, unevenly spaced.
   o.dipX/dipW/dipK open a notch in the roofline — the block steps down
   toward the light so the low sun is not simply walled off. Without it
   a 200-unit skyline swallows a sun sitting 80 units above the horizon. */
function cityBand(x0, x1, C, seed, o) {
  var r = R(seed), x = x0, s = '', w, h, d,
      dx = o.dipX !== undefined ? o.dipX : C.dipX,                   // defaults come off the
      dw = o.dipW !== undefined ? o.dipW : C.dipW,                   // layer, so the notch is
      dk = o.dipK !== undefined ? o.dipK : C.dipK;                   // part of the light model
  while (x < x1) {
    w = o.wmin + r() * (o.wmax - o.wmin);
    h = o.hmin + r() * (o.hmax - o.hmin);
    if (r() < 0.13) h *= 1.42;                                       // the occasional spike
    if (dw) {                                                        // the notch under the sun
      d = Math.abs(x + w / 2 - dx) / dw;
      if (d < 1) h *= dk + (1 - dk) * d * d;
    }
    s += tower(x, w, h, C, seed + Math.round(x) * 13 + 3, o);
    x += w * (r() < 0.55 ? 0.68 + r() * 0.22 : 1.06 + r() * 0.5);    // overlap, then a gap
  }
  return s;
}

/* ==================================================================
   4. Foreground furniture (near layer, near-black, oversized)
   ================================================================== */
function parapet(y, f, rim) {                                        // low coping wall, kept thin
  return rect(-140, y, 1880, G - y + 8, f) + rect(-140, y - 9, 1880, 11, f) + rect(-140, y - 10, 1880, 3, rim, ' opacity="0.28"');
}
/* see-through balustrade above the coping — stops the base going solid black */
function balusters(yTop, yBot, f, rim, step, w) {
  return rect(-140, yTop, 1880, 8, f) + rect(-140, yTop - 1.5, 1880, 2.5, rim, ' opacity="0.22"') +
    loop(Math.ceil(1880 / step), function (i) { return rect(-140 + i * step, yTop + 6, w, yBot - yTop - 6, f); });
}
/* close, near-black block with a real parapet, plant and antenna */
function nearBlock(x, w, h, C, seed, crown) { return tower(x, w, h, C, seed, { setbacks: 0, crown: crown || 'flat' }); }
function bigLamp(x, headY, f, rim) {                                 // deliberately huge: the scale jump
  var s = rect(x - 11, headY + 40, 22, G - headY - 40, f) + rect(x - 26, G - 46, 52, 46, f) + rect(x - 20, G - 300, 40, 16, f);
  s += strk('M' + x + ' ' + (headY + 52) + ' q0 -46 54 -46', f, 13);
  s += poly(pts([x + 40, headY - 2, x + 68, headY - 2, x + 62, headY + 30, x + 46, headY + 30]), f);
  s += circ(x + 54, headY + 16, 13, AMBER, ' opacity="0.8"') + circ(x + 54, headY + 16, 44, AMBER, ' opacity="0.1"');
  return s + rect(x - 11, headY + 40, 3, G - headY - 40, rim, ' opacity="0.22"');
}
function scrub(seed, n, f, x0, x1) {
  var r = R(seed), s = '', i, x;
  for (i = 0; i < n; i++) { x = x0 + r() * (x1 - x0); s += elli(x, G + 6, 26 + r() * 58, 12 + r() * 26, f); }
  return s;
}
function grass(seed, n, f, x0, x1) {
  var r = R(seed);
  return loop(n, function () { var x = x0 + r() * (x1 - x0), hh = 16 + r() * 26; return strk('M' + nn(x) + ' ' + (G + 6) + ' q' + nn(-4 + r() * 8) + ' ' + nn(-hh * 0.6) + ' ' + nn(-8 + r() * 16) + ' ' + nn(-hh), f, 3, 1, true); });
}

/* ==================================================================
   5. Landmarks
   ================================================================== */
/* --- New York --------------------------------------------------- */
function empireState(cx, h, C) {                                     // base, wings, shaft, setbacks, mast
  var f = C.fill, w = h * 0.29, s = '', y = G, i, ww;
  s += rect(cx - w * 1.02, G - h * 0.15, w * 2.04, h * 0.15, f) + winGrid(cx - w * 1.02, G - h * 0.15, w * 2.04, h * 0.15, 771, C);
  y = G - h * 0.15;
  s += rect(cx - w * 0.75, y - h * 0.09, w * 1.5, h * 0.09, f) + winGrid(cx - w * 0.75, y - h * 0.09, w * 1.5, h * 0.09, 773, C);
  y -= h * 0.09;
  s += rect(cx - w / 2, y - h * 0.48, w, h * 0.48, f) + winGrid(cx - w / 2, y - h * 0.48, w, h * 0.48, 775, C) + piers(cx - w / 2, y - h * 0.48, w, h * 0.48, C.rim, 0.15);
  y -= h * 0.48; ww = w;
  for (i = 0; i < 3; i++) { ww *= 0.8; s += rect(cx - ww / 2, y - h * 0.04, ww, h * 0.04 + 2, f) + rect(cx - ww / 2, y - h * 0.04 - 2, ww, 2.5, C.rim, ' opacity="0.3"'); y -= h * 0.04; }
  s += poly(pts([cx - ww * 0.5, y + 2, cx - ww * 0.15, y - h * 0.11, cx + ww * 0.15, y - h * 0.11, cx + ww * 0.5, y + 2]), f);
  y -= h * 0.11;
  s += rect(cx - ww * 0.2, y - h * 0.03, ww * 0.4, h * 0.03 + 2, f) + rect(cx - 2.5, y - h * 0.13, 5, h * 0.1, f);
  s += circ(cx, y - h * 0.13, 3.6, AMBER, ' opacity="0.85"');
  s += rect(cx + w / 2 - 3, G - h * 0.72, 3, h * 0.48, C.rim, ' opacity="' + C.rimOp + '"');
  return s;
}
function chrysler(cx, h, C) {                                        // stepped arc crown + needle
  var f = C.fill, w = h * 0.17, s = '', y = G - h * 0.7, i, ww, hh;
  s += rect(cx - w / 2, y, w, h * 0.7, f) + winGrid(cx - w / 2, y, w, h * 0.7, 781, C) + piers(cx - w / 2, y, w, h * 0.7, C.rim, 0.16);
  for (i = 0; i < 5; i++) {
    ww = w * (1 - i * 0.16); hh = h * 0.05;
    s += pathd('M' + nn(cx - ww / 2) + ' ' + nn(y + 1) + ' A' + nn(ww / 2) + ' ' + nn(hh * 1.7) + ' 0 0 1 ' + nn(cx + ww / 2) + ' ' + nn(y + 1) + ' Z', f);
    s += ln(cx - ww * 0.3, y - hh * 0.9, cx + ww * 0.3, y - hh * 0.9, C.rim, 1.5, 0.3);
    y -= hh;
  }
  return s + rect(cx - 2, y - h * 0.14, 4, h * 0.15, f) + circ(cx, y - h * 0.14, 3, AMBER, ' opacity="0.8"');
}
function waterTower(x, roofY, sc, f, rim) {
  var w = 30 * sc, h = 34 * sc, leg = 17 * sc, top = roofY - leg - h;
  return rect(x + 3, top + h, 5 * sc, leg, f) + rect(x + w - 8 * sc, top + h, 5 * sc, leg, f) + rect(x + w / 2 - 2, top + h, 4, leg, f) +
    rect(x, top, w, h, f) + poly(pts([x - 6 * sc, top + 2, x + w / 2, top - 20 * sc, x + w + 6 * sc, top + 2]), f) +
    rect(x + w - 3, top, 3, h, rim, ' opacity="0.3"');
}

/* --- Iran ------------------------------------------------------- */
function ogive(x, w, spring, apex) {                                 // two-centre pointed arch
  var d = spring - apex;
  return 'M' + nn(x) + ' ' + nn(spring) + ' Q' + nn(x) + ' ' + nn(spring - d * 0.74) + ' ' + nn(x + w / 2) + ' ' + nn(apex) +
    ' Q' + nn(x + w) + ' ' + nn(spring - d * 0.74) + ' ' + nn(x + w) + ' ' + nn(spring);
}
function archHole(cx, w, baseY, h) {                                 // round-arch cut-out subpath
  var x = cx - w / 2, r = w / 2;
  return 'M' + nn(x) + ' ' + nn(baseY) + ' L' + nn(x) + ' ' + nn(baseY - h + r) + ' A' + nn(r) + ' ' + nn(r) + ' 0 0 1 ' + nn(x + w) + ' ' + nn(baseY - h + r) + ' L' + nn(x + w) + ' ' + nn(baseY) + ' Z';
}
function onion(cx, baseY, w, h) {                                    // bulbous Persian dome
  var hw = w / 2;
  return 'M' + nn(cx - hw) + ' ' + nn(baseY) +
    ' C' + nn(cx - hw * 1.26) + ' ' + nn(baseY - h * 0.40) + ' ' + nn(cx - hw * 0.62) + ' ' + nn(baseY - h * 0.80) + ' ' + nn(cx) + ' ' + nn(baseY - h) +
    ' C' + nn(cx + hw * 0.62) + ' ' + nn(baseY - h * 0.80) + ' ' + nn(cx + hw * 1.26) + ' ' + nn(baseY - h * 0.40) + ' ' + nn(cx + hw) + ' ' + nn(baseY) + ' Z';
}
function minaret(x, h, C) {
  var f = C.fill, w = h * 0.052, y = G - h, s = '';
  s += poly(pts([x - w * 0.72, G, x + w * 0.72, G, x + w / 2, y + h * 0.28, x - w / 2, y + h * 0.28]), f);
  s += rect(x - w * 0.44, y + 46, w * 0.88, h * 0.28 - 46 + 2, f);
  s += rect(x - w * 0.95, y + 38, w * 1.9, 9, f) + rect(x - w * 0.95, y + 36, w * 1.9, 2.5, C.rim, ' opacity="0.35"');
  s += rect(x - w * 0.42, y + 8, w * 0.84, 32, f) + pathd(onion(x, y + 10, w * 1.5, 32), f);
  s += rect(x - 2, y - 30, 4, 22, f) + circ(x, y - 34, 3.4, AMBER, ' opacity="0.7"');
  s += rect(x + w * 0.44 - 3, y + 46, 3, h * 0.28 - 46, C.rim, ' opacity="' + C.rimOp + '"');
  return s;
}
function iwan(cx, w, h, C) {                                         // portal screen with a deep pointed arch
  var f = C.fill, x = cx - w / 2, top = G - h, ix = cx - w * 0.28, iw = w * 0.56;
  var d = 'M' + nn(x) + ' ' + G + ' L' + nn(x) + ' ' + nn(top) + ' L' + nn(x + w) + ' ' + nn(top) + ' L' + nn(x + w) + ' ' + G + ' Z';
  d += ' M' + nn(ix) + ' ' + G + ' L' + ogive(ix, iw, G - h * 0.46, G - h * 0.86).slice(1) + ' L' + nn(ix + iw) + ' ' + G + ' Z';
  return pathd(d, f, ' fill-rule="evenodd"') +
    rect(x, top - 8, w, 9, f) + rect(x, top - 9, w, 3, C.rim, ' opacity="0.3"') +
    rect(x + w - 3, top, 3, h, C.rim, ' opacity="' + C.rimOp + '"') +
    loop(2, function (i) { return rect(i ? x + w - 16 : x, top, 16, h, f); });
}
function palm(x, h, f, seed, sc) {
  var r = R(seed), top = G - h, tw = 7 * (sc || 1);
  return pathd('M' + nn(x - tw) + ' ' + G + ' Q' + nn(x - tw * 2.6) + ' ' + nn(G - h * 0.52) + ' ' + nn(x - tw * 0.5) + ' ' + nn(top) +
    ' L' + nn(x + tw * 0.9) + ' ' + nn(top) + ' Q' + nn(x - tw * 0.6) + ' ' + nn(G - h * 0.52) + ' ' + nn(x + tw * 1.2) + ' ' + G + ' Z', f) +
    loop(9, function (i) {
      var a = -2.86 + i * 0.6, len = (52 + r() * 34) * (sc || 1), bx = x + Math.cos(a) * len, by = top + Math.sin(a) * len * 0.78;
      return strk('M' + nn(x) + ' ' + nn(top) + ' Q' + nn(x + Math.cos(a) * len * 0.55) + ' ' + nn(top + Math.sin(a) * len * 0.42 - 18 * (sc || 1)) + ' ' + nn(bx) + ' ' + nn(by), f, 6 * (sc || 1), 1, true);
    });
}

/* --- China ------------------------------------------------------ */
function eaves(cx, y, w, h, f) {                                     // upswept tiled roof
  var hw = w / 2;
  return pathd('M' + nn(cx) + ' ' + nn(y - h) +
    ' Q' + nn(cx - hw * 0.4) + ' ' + nn(y - h * 0.52) + ' ' + nn(cx - hw) + ' ' + nn(y - h * 0.26) +
    ' Q' + nn(cx - hw * 0.52) + ' ' + nn(y + 3) + ' ' + nn(cx) + ' ' + nn(y + 3) +
    ' Q' + nn(cx + hw * 0.52) + ' ' + nn(y + 3) + ' ' + nn(cx + hw) + ' ' + nn(y - h * 0.26) +
    ' Q' + nn(cx + hw * 0.4) + ' ' + nn(y - h * 0.52) + ' ' + nn(cx) + ' ' + nn(y - h) + ' Z', f);
}
function pagoda(cx, baseW, tiers, tierH, C, sorin) {
  var f = C.fill, s = '', i, w, y = G;
  for (i = 0; i < tiers; i++) {
    w = baseW * (1 - i * (0.55 / tiers));
    s += rect(cx - w * 0.32, y - tierH, w * 0.64, tierH, f);
    s += rect(cx + w * 0.32 - 3, y - tierH, 3, tierH, C.rim, ' opacity="' + C.rimOp + '"');
    if (i < 2) s += rect(cx - w * 0.1, y - tierH * 0.62, w * 0.2, tierH * 0.42, AMBER, ' opacity="0.18"');
    s += eaves(cx, y - tierH, w, tierH * 0.66, f);
    y -= tierH;
  }
  s += rect(cx - 3, y - 40, 6, 42, f);
  if (sorin) s += loop(5, function (i) { return elli(cx, y - 8 - i * 7, 9 - i * 1.2, 2, f); });
  return s + circ(cx, y - 46, 6, f);
}
function pearlTower(cx, h, C) {                                      // Oriental Pearl: 3 legs, 3 spheres
  var f = C.fill, top = G - h, s = '', i;
  for (i = -1; i <= 1; i += 2) s += poly(pts([cx + i * 78, G, cx + i * 50, G, cx + i * 9, G - h * 0.34, cx + i * 24, G - h * 0.34]), f);
  s += rect(cx - 4, G - h * 0.3, 8, h * 0.3, f);
  s += rect(cx - 13, top + h * 0.1, 26, h * 0.9, f);
  s += circ(cx, G - h * 0.22, h * 0.115, f) + circ(cx, G - h * 0.22, h * 0.115, C.rim, ' opacity="0.16"');
  s += circ(cx, G - h * 0.60, h * 0.085, f);
  s += circ(cx, G - h * 0.82, h * 0.042, f);
  s += rect(cx - 2.5, top - h * 0.14, 5, h * 0.15, f) + circ(cx, top - h * 0.14, 3.6, AMBER, ' opacity="0.9"');
  s += rect(cx + 10, top + h * 0.1, 3, h * 0.9, C.rim, ' opacity="' + C.rimOp + '"');
  return s;
}
function gate(cx, w, h, C) {                                         // ceremonial gate, 5 arches, double roof
  var f = C.fill, base = h * 0.46, x = cx - w / 2, i,
      d = 'M' + nn(x) + ' ' + G + ' L' + nn(x) + ' ' + nn(G - base) + ' L' + nn(x + w) + ' ' + nn(G - base) + ' L' + nn(x + w) + ' ' + G + ' Z';
  d += ' ' + archHole(cx, w * 0.15, G, base * 0.72);
  for (i = 1; i <= 2; i++) d += ' ' + archHole(cx - w * 0.21 * i, w * 0.1, G, base * 0.52) + ' ' + archHole(cx + w * 0.21 * i, w * 0.1, G, base * 0.52);
  return pathd(d, f, ' fill-rule="evenodd"') +
    rect(x - w * 0.02, G - base - 10, w * 1.04, 11, f) +
    rect(cx - w * 0.38, G - h, w * 0.76, h - base - 10, f) +
    loop(7, function (i) { return rect(cx - w * 0.34 + i * w * 0.096, G - h + 22, w * 0.05, h - base - 40, AMBER, ' opacity="0.14"'); }) +
    eaves(cx, G - h, w * 1.1, h * 0.26, f) + eaves(cx, G - h - h * 0.2, w * 0.8, h * 0.2, f);
}
function lanternRow(y0, x0, x1, n, f, id, sc) {                      // hung from above; deliberately oversized
  return loop(n, function (i) {
    var t = n < 2 ? 0.5 : i / (n - 1), x = x0 + (x1 - x0) * t,
        y = y0 + Math.sin(Math.PI * t) * 64 + (i % 2) * 58, rx = 30 * sc, ry = 38 * sc, cy = y + ry + 8 * sc;
    return ln(x, -20, x, y, f, 3, 0.8) + circ(x, cy, 132 * sc, 'url(#' + id + ')') +
      elli(x, cy, rx, ry, AMBER, ' opacity="0.34"') +
      loop(3, function (k) { return ln(x - rx * 0.6 + k * rx * 0.6, cy - ry * 0.86, x - rx * 0.6 + k * rx * 0.6, cy + ry * 0.86, f, 2.5, 0.35); }) +
      rect(x - rx * 0.62, y + 2 * sc, rx * 1.24, 10 * sc, f) + rect(x - rx * 0.62, cy + ry - 4 * sc, rx * 1.24, 10 * sc, f) +
      strk('M' + nn(x) + ' ' + nn(cy + ry + 6 * sc) + ' l0 ' + nn(32 * sc), f, 3.5 * sc, 0.85);
  });
}

/* --- Euro area -------------------------------------------------- */
function star(cx, cy, r, points, rot) {
  points = points || 5;
  var inner = r * (points === 5 ? 0.382 : 0.55), a = [], i, ang;
  for (i = 0; i < points * 2; i++) { ang = (rot === undefined ? -Math.PI / 2 : rot) + i * Math.PI / points; a.push(cx + Math.cos(ang) * (i % 2 ? inner : r), cy + Math.sin(ang) * (i % 2 ? inner : r)); }
  return pts(a);
}
function messeturm(cx, h, C) {                                       // square shaft + tall pyramid cap
  var f = C.fill, w = h * 0.2, s = rect(cx - w * 0.62, G - h * 0.3, w * 1.24, h * 0.3, f) + winGrid(cx - w * 0.62, G - h * 0.3, w * 1.24, h * 0.3, 611, C);
  s += rect(cx - w / 2, G - h * 0.76, w, h * 0.46, f) + winGrid(cx - w / 2, G - h * 0.76, w, h * 0.46, 613, C);
  s += rect(cx - w * 0.4, G - h * 0.82, w * 0.8, h * 0.06 + 2, f);
  s += poly(pts([cx - w * 0.4, G - h * 0.82, cx, G - h, cx + w * 0.4, G - h * 0.82]), f);
  s += rect(cx - 2, G - h * 1.06, 4, h * 0.07, f) + circ(cx, G - h * 1.06, 3, AMBER, ' opacity="0.8"');
  return s + rect(cx + w / 2 - 3, G - h * 0.76, 3, h * 0.46, C.rim, ' opacity="' + C.rimOp + '"');
}
function colonnade(x, w, h, n, f, rim) {                             // classical portico, close and large
  var colW = w / (n * 1.75), gap = (w - colW * n) / (n - 1), s = rect(x - 22, G - 26, w + 44, 26, f), i, cx;
  for (i = 0; i < n; i++) {
    cx = x + i * (colW + gap);
    s += rect(cx, G - h + 34, colW, h - 60, f) + rect(cx - 5, G - h + 24, colW + 10, 12, f) +
      rect(cx + colW - 3, G - h + 34, 3, h - 60, rim, ' opacity="0.2"');
  }
  return s + rect(x - 26, G - h - 6, w + 52, 32, f) + rect(x - 26, G - h - 7, w + 52, 3, rim, ' opacity="0.25"') +
    poly(pts([x - 44, G - h - 5, x + w / 2, G - h - 92, x + w + 44, G - h - 5]), f);
}

/* --- United Kingdom --------------------------------------------- */
function elizabethTower(cx, h, C, id) {                              // clock at ~58%, belfry, spire
  var f = C.fill, w = h * 0.125, y = G - h, cy = G - h * 0.585, s = '';
  s += rect(cx - w * 0.62, G - h * 0.1, w * 1.24, h * 0.1, f);
  s += rect(cx - w / 2, G - h * 0.63, w, h * 0.53, f) + piers(cx - w / 2, G - h * 0.63, w, h * 0.53, C.rim, 0.16);
  s += rect(cx - w * 0.58, G - h * 0.685, w * 1.16, h * 0.06, f);
  s += circ(cx, cy, w * 0.46, 'url(#' + id + ')');
  s += circ(cx, cy, w * 0.33, mix(BONE, AMBER, 0.35), ' opacity="0.9"') + circ(cx, cy, w * 0.33, 'none', ' stroke="' + f + '" stroke-width="2.5"');
  s += ln(cx, cy, cx, cy - w * 0.22, f, 2.6, 0.95) + ln(cx, cy, cx + w * 0.15, cy + w * 0.09, f, 2.6, 0.95);
  s += rect(cx - w * 0.5, G - h * 0.79, w, h * 0.105, f) + loop(3, function (i) { return rect(cx - w * 0.36 + i * w * 0.26, G - h * 0.775, w * 0.14, h * 0.08, AMBER, ' opacity="0.13"'); });
  s += rect(cx - w * 0.56, G - h * 0.8, w * 1.12, h * 0.02, f);
  s += poly(pts([cx - w * 0.5, G - h * 0.8, cx, G - h * 0.985, cx + w * 0.5, G - h * 0.8]), f);
  s += rect(cx - 2, y - h * 0.03, 4, h * 0.05, f) + circ(cx, y - h * 0.035, 3, AMBER, ' opacity="0.75"');
  return s + rect(cx + w / 2 - 3, G - h * 0.63, 3, h * 0.53, C.rim, ' opacity="' + C.rimOp + '"');
}
function gherkin(cx, h, C, id) {                                     // real taper: widest ~30% up, domed cap
  var wMax = h * 0.30, p = profile(cx, h * 0.96, function (t) { return wMax * Math.pow(Math.sin(Math.PI * (0.32 + 0.63 * t)), 0.55); }, 34, C.fill);
  var s = '<defs><clipPath id="' + id + '"><polygon points="' + p.pts + '"/></clipPath></defs>' + p.svg;
  s += '<g clip-path="url(#' + id + ')">';
  s += loop(9, function (i) { return ln(cx - wMax * 1.2, G - i * h * 0.13 + h * 0.2, cx + wMax * 1.2, G - i * h * 0.13 - h * 0.1, C.rim, 1.6, 0.16); });
  s += loop(9, function (i) { return ln(cx - wMax * 1.2, G - i * h * 0.13 - h * 0.1, cx + wMax * 1.2, G - i * h * 0.13 + h * 0.2, C.rim, 1.6, 0.16); });
  s += rect(cx, G - h, wMax * 1.2, h, C.rim, ' opacity="' + (C.rimOp * 0.55).toFixed(2) + '"');
  s += winGrid(cx - wMax * 0.7, G - h * 0.8, wMax * 1.4, h * 0.7, 721, C);
  s += '</g>';
  return s + circ(cx, G - h * 0.955, wMax * 0.17, C.fill) + circ(cx, G - h * 0.985, 5, AMBER, ' opacity="0.5"');
}
function shard(cx, h, C) {                                           // tapering facets, splintered open top
  var w = h * 0.19, p = profile(cx, h * 0.86, function (t) { return w * Math.pow(1 - t, 1.05) + 3; }, 12, C.fill), s = p.svg, i;
  for (i = 0; i < 5; i++) s += poly(pts([cx - w * 0.16 + i * w * 0.08 - 4, G - h * 0.86, cx - w * 0.13 + i * w * 0.08, G - h * (0.9 + (i % 3) * 0.035), cx - w * 0.1 + i * w * 0.08 + 2, G - h * 0.86]), C.fill);
  for (i = 1; i < 5; i++) s += ln(cx - w + i * w * 0.5, G, cx + w * 0.04, G - h * 0.86, C.rim, 1.4, 0.13);
  s += winGrid(cx - w * 0.72, G - h * 0.7, w * 1.44, h * 0.66, 731, C);
  return s + poly(pts([cx + w * 0.62, G, cx + w * 0.04, G - h * 0.84, cx + w * 0.1, G - h * 0.84, cx + w * 0.72, G]), C.rim, ' opacity="' + (C.rimOp * 0.7).toFixed(2) + '"');
}
function drizzle(seed, n, colour) {
  var r = R(seed), s = '', i, x, y, l;
  for (i = 0; i < n; i++) { x = -80 + r() * 1760; y = r() * G; l = 16 + r() * 34; s += ln(x, y, x - 9, y + l, colour || BONE, 1, (0.03 + r() * 0.08).toFixed(2)); }
  return s;
}

/* --- Japan ------------------------------------------------------ */
function fuji(cx, bh, h, C) {                                        // shallow, concave, real Fuji ratio
  return profile(cx, h, function (t) { return 46 + (bh - 46) * Math.pow(1 - t, 1.5); }, 44, C.fill).svg;
}
function snowCap(cx, top, w0, w1, drop, colour, seed) {
  var r = R(seed), a = [cx - w0, top + 1, cx + w0, top + 1, cx + w1, top + drop], i, n = 17, t;
  for (i = 1; i < n; i++) { t = cx + w1 - 2 * w1 * (i / n); a.push(t, top + drop + (i % 2 ? 9 + r() * 15 : -3 - r() * 5)); }
  a.push(cx - w1, top + drop);
  return poly(pts(a), colour, ' opacity="0.4"');
}
function torii(cx, w, h, f, rim) {                                   // leaning posts, curved kasagi, nuki
  var hw = w / 2, top = G - h, pw = w * 0.075;
  return poly(pts([cx - hw - pw, G, cx - hw + pw, G, cx - hw + pw * 0.72, top + h * 0.09, cx - hw - pw * 0.72, top + h * 0.09]), f) +
    poly(pts([cx + hw + pw, G, cx + hw - pw, G, cx + hw - pw * 0.72, top + h * 0.09, cx + hw + pw * 0.72, top + h * 0.09]), f) +
    rect(cx - hw - pw * 1.5, top + h * 0.24, w + pw * 3, h * 0.05, f) +
    rect(cx - w * 0.045, top + h * 0.07, w * 0.09, h * 0.19, f) +
    pathd('M' + nn(cx - hw - w * 0.19) + ' ' + nn(top + h * 0.06) + ' Q' + nn(cx) + ' ' + nn(top - h * 0.05) + ' ' + nn(cx + hw + w * 0.19) + ' ' + nn(top + h * 0.06) +
      ' L' + nn(cx + hw + w * 0.17) + ' ' + nn(top + h * 0.135) + ' Q' + nn(cx) + ' ' + nn(top + h * 0.025) + ' ' + nn(cx - hw - w * 0.17) + ' ' + nn(top + h * 0.135) + ' Z', f) +
    rect(cx + hw - pw, top + h * 0.09, 3, h * 0.91, rim, ' opacity="0.18"');
}
function pineBranch(x0, y0, x1, y1, f, seed) {                       // oversized foreground limb + needle fans
  var r = R(seed);
  return strk('M' + x0 + ' ' + y0 + ' Q' + nn((x0 + x1) / 2 + 60) + ' ' + nn(y0 + (y1 - y0) * 0.8) + ' ' + x1 + ' ' + y1, f, 15, 1, true) +
    loop(8, function (i) {
      var t = 0.14 + i * 0.108, bx = x0 + (x1 - x0) * t, by = y0 + (y1 - y0) * (0.55 * t + 0.45 * t * t);
      return loop(5, function (k) {
        var a = -0.5 + k * 0.52 + (i % 2 ? 0.22 : -0.22), L = 32 + r() * 34;
        return strk('M' + nn(bx) + ' ' + nn(by) + ' l' + nn(-Math.cos(a) * L) + ' ' + nn(Math.sin(a) * L), f, 5, 1, true);
      });
    });
}

/* --- Global ----------------------------------------------------- */
function globe(cx, cy, r, id, colour) {
  return '<defs><clipPath id="' + id + '"><rect x="-140" y="0" width="1880" height="' + G + '"/></clipPath></defs>' +
    '<g clip-path="url(#' + id + ')" fill="none" stroke="' + (colour || BONE) + '">' +
    '<circle cx="' + cx + '" cy="' + cy + '" r="' + r + '" stroke-width="2" opacity="0.26"/>' +
    loop(7, function (i) { var lat = (i - 3) * Math.PI / 8, rx = r * Math.cos(lat);
      return '<ellipse cx="' + cx + '" cy="' + nn(cy - r * Math.sin(lat) * 0.96) + '" rx="' + nn(rx) + '" ry="' + nn(rx * 0.28) + '" stroke-width="1.3" opacity="0.15"/>'; }) +
    loop(6, function (i) { return '<ellipse cx="' + cx + '" cy="' + cy + '" rx="' + nn(Math.abs(r * Math.cos(i * Math.PI / 6))) + '" ry="' + r + '" stroke-width="1.3" opacity="0.15"/>'; }) +
    '</g>';
}

/* --- India ------------------------------------------------------ */
/* A shouldered dome. `onion` already draws a dome, but a Persian onion
   pinches in above the springing and the Indo-Saracenic dome does the
   opposite — it swells past the springing line and then flattens — so
   reusing Isfahan's curve here would make Mumbai look like Isfahan. */
function dome(cx, baseY, w, h) {
  var hw = w / 2;
  return 'M' + nn(cx - hw) + ' ' + nn(baseY) +
    ' C' + nn(cx - hw * 1.04) + ' ' + nn(baseY - h * 0.62) + ' ' + nn(cx - hw * 0.56) + ' ' + nn(baseY - h) + ' ' + nn(cx) + ' ' + nn(baseY - h) +
    ' C' + nn(cx + hw * 0.56) + ' ' + nn(baseY - h) + ' ' + nn(cx + hw * 1.04) + ' ' + nn(baseY - h * 0.62) + ' ' + nn(cx + hw) + ' ' + nn(baseY) + ' Z';
}
/* Domed corner kiosk. At silhouette scale a chhatri is four legs and a
   dome, and that is the whole job: it is what stops an Indian roofline
   reading as the same flat parapet every other region already has. */
function chhatri(cx, baseY, w, h, f) {
  var hw = w / 2;
  return rect(cx - hw, baseY - 5, w, 6, f) +
    loop(4, function (i) { return rect(cx - hw + 3 + i * ((w - 9) / 3), baseY - h * 0.44, 3.5, h * 0.44, f); }) +
    rect(cx - hw * 1.14, baseY - h * 0.5, w * 1.14, 6, f) +
    pathd(dome(cx, baseY - h * 0.5, w * 0.88, h * 0.46), f) +
    rect(cx - 1.5, baseY - h * 1.04, 3, h * 0.12, f);
}
/* The Gateway of India: one tall round arch between two turrets, with
   a dome over the centre. Cut as a single evenodd path so the openings
   are real holes — this thing stands right beside the bloom, and an
   arch that does not let the sky through goes flat the moment it does. */
function gateway(cx, w, h, C) {
  var f = C.fill, rim = C.rim, body = h * 0.58, x = cx - w / 2,
      tw = w * 0.13, th = h * 0.80, dw = w * 0.46, dh = h * 0.27, drum = h * 0.06,
      d = 'M' + nn(x) + ' ' + G + ' L' + nn(x) + ' ' + nn(G - body) + ' L' + nn(x + w) + ' ' + nn(G - body) + ' L' + nn(x + w) + ' ' + G + ' Z', s;
  d += ' ' + archHole(cx, w * 0.32, G, body * 0.88);
  d += ' ' + archHole(cx - w * 0.30, w * 0.10, G, body * 0.42) + ' ' + archHole(cx + w * 0.30, w * 0.10, G, body * 0.42);
  s = pathd(d, f, ' fill-rule="evenodd"');
  s += rect(x - w * 0.035, G - body - 13, w * 1.07, 14, f) + rect(x - w * 0.035, G - body - 14, w * 1.07, 3, rim, ' opacity="0.26"');
  s += loop(2, function (i) {                                        // the flanking turrets
    var tx = cx + (i ? 1 : -1) * w * 0.425;
    return rect(tx - tw / 2, G - th, tw, th, f) +
      rect(tx - tw * 0.72, G - th - 8, tw * 1.44, 9, f) +
      pathd(dome(tx, G - th - 8, tw * 1.3, tw * 1.1), f) +
      rect(tx - 1.5, G - th - 8 - tw * 1.1 - 12, 3, 13, f);
  });
  s += rect(cx - dw * 0.42, G - body - 13 - drum, dw * 0.84, drum + 2, f);
  s += pathd(dome(cx, G - body - 13 - drum, dw, dh), f);
  s += rect(cx - 2.5, G - body - 13 - drum - dh - 17, 5, 18, f) + circ(cx, G - body - 13 - drum - dh - 19, 4, AMBER, ' opacity="0.7"');
  s += rect(x + w - 4, G - body, 4, body, rim, ' opacity="' + C.rimOp + '"');
  s += rect(cx + w * 0.425 + tw / 2 - 3, G - th, 3, th, rim, ' opacity="' + C.rimOp + '"');
  return s;
}

/* --- Gold ------------------------------------------------------- */
/* A mine has no skyline, so spoil heaps take the place the city bands
   hold everywhere else — something for the haze to eat into. A lazy
   random walk rather than per-step noise, because waste rock piles up
   in a few broad angular heaps and never in a sawtooth. */
function ridge(seed, C, base, amp, x0, x1, pitch) {
  var r = R(seed), a = [x0, G + 24], x, v = 0.45;
  for (x = x0; x <= x1; x += pitch) {
    v += (r() - 0.5) * 0.64; v = v < 0 ? 0 : (v > 1 ? 1 : v);
    a.push(x, G - base - v * amp);
  }
  a.push(x1, G + 24);
  return poly(pts(a), C.fill);
}
/* Terraced bench face — the cut side of an open pit, stepping back as
   it rises. In silhouette a hill and a pit are the same triangle, so
   everything here exists to break that triangle up: each lift is drawn
   a step lighter than the one below it, and every bench floor takes a
   hard lit edge. A pit is a dozen stacked lit lines; a hill is one.
   The zig-zag across the lifts is the haul road. */
function benches(cx, halfW, top, n, C, seed, lean) {
  var r = R(seed), s = '', lift = (G - top) / n, i, y0, y1, w0, w1, j0, j1, l0, l1, f;
  lean = lean || 0;
  for (i = 0; i < n; i++) {
    y0 = G - i * lift; y1 = y0 - lift;
    w0 = halfW * (1 - (i / n) * 0.74);
    w1 = halfW * (1 - ((i + 1) / n) * 0.74);
    j0 = (r() - 0.5) * halfW * 0.09; j1 = (r() - 0.5) * halfW * 0.09;
    l0 = lean * i; l1 = lean * (i + 1);
    f = mix(C.fill, C.haze, 0.035 + i * 0.05);                       // each lift a step lighter than the one below
    s += poly(pts([cx - w0 + j0 + l0, y0 + 3, cx + w0 + j0 + l0, y0 + 3, cx + w1 + j1 + l1, y1, cx - w1 + j1 + l1, y1]), f);
    s += rect(cx - w1 + j1 + l1, y1 - 2.5, w1 * 2, 4.5, C.rim, ' opacity="' + Math.min(0.9, C.rimOp * 1.35).toFixed(2) + '"');
    s += rect(cx - w1 + j1 + l1, y1 + 2, w1 * 2, lift * 0.14, C.rim, ' opacity="' + (C.rimOp * 0.3).toFixed(2) + '"');
    s += ln(i % 2 ? cx - w0 + j0 + l0 : cx + w0 + j0 + l0, y0, i % 2 ? cx + w1 + j1 + l1 : cx - w1 + j1 + l1, y1, C.rim, 3.6, 0.2);
  }
  return s;
}
/* A waste bank: the same rock as `benches` but dumped rather than cut,
   so it has no steps and no lit edges — just an irregular crest that
   runs off the side of the frame. Used where the scene needs mass
   without drawing the eye, which is to say on the copy side. */
function bank(seed, C, x0, x1, base, amp, pitch) {
  var r = R(seed), a = [x0, G + 24], x, v = 0.8, t;
  for (x = x0; x <= x1; x += pitch) {
    t = (x1 - x) / (x1 - x0);                                        // taper into the ground at the open end
    v += (r() - 0.5) * 0.5; v = v < 0.15 ? 0.15 : (v > 1 ? 1 : v);
    a.push(x, G - (base + v * amp) * t * t);
  }
  a.push(x1, G + 24);
  return poly(pts(a), C.fill);
}
/* Inclined conveyor gantry, pit to mill. An open truss on trestles: a
   solid ramp at this size would be a wall across the sun, and the
   point of the gantry is that the light comes through it. */
function conveyor(x0, y0, x1, y1, C, depth) {
  var dx = x1 - x0, dy = y1 - y0, L = Math.sqrt(dx * dx + dy * dy),
      ux = dx / L, uy = dy / L, nx = uy, ny = -ux, d = depth || 24,
      n = Math.max(4, Math.round(L / 36)), s = '', i, t, bx, by,
      tx = nn(x0 + nx * d) + ' ' + nn(y0 + ny * d) + ' L' + nn(x1 + nx * d) + ' ' + nn(y1 + ny * d);
  s += strk('M' + nn(x0) + ' ' + nn(y0) + ' L' + nn(x1) + ' ' + nn(y1), C.fill, 7);
  s += strk('M' + tx, C.fill, 7);
  for (i = 0; i < n; i++) {                                          // the diagonals of the truss
    t = i / n; bx = x0 + dx * t; by = y0 + dy * t;
    s += strk('M' + nn(bx) + ' ' + nn(by) + ' L' + nn(bx + dx / n + nx * d) + ' ' + nn(by + dy / n + ny * d), C.fill, 3, 0.9);
  }
  for (i = 1; i <= 3; i++) {                                         // trestles down to the ground
    t = i / 4.2; bx = x0 + dx * t; by = y0 + dy * t;
    s += poly(pts([bx - 11, G, bx - 4, by, bx + 4, by, bx + 11, G]), C.fill) +
      rect(bx + 1.5, by, 3.5, G - by + 4, C.rim, ' opacity="' + (C.rimOp * 0.55).toFixed(2) + '"');
  }
  return s + strk('M' + tx, C.rim, 2.2, Math.min(0.9, C.rimOp * 1.1).toFixed(2));
}
/* The headframe. Everything else on a mine site is a heap, so this is
   the one piece of engineering and it carries the detail: battered
   legs, the raking back-brace that takes the hoist rope, and the
   sheave wheel, which is the single shape that says "mine" at a glance.
   `brace` picks the side the back-leg rakes to, so the frame can be
   turned away from the sun instead of fencing it off. */
function headframe(cx, h, C, seed, brace) {
  var f = C.fill, rim = C.rim, top = G - h, w = h * 0.30, s = '',
      sr = h * 0.115, sy = top - sr * 0.92, bx0, by0, bx1, by1;
  brace = brace === undefined ? -1 : brace;
  function legX(side, u) { return cx + side * (w / 2 - (w / 2 - w * 0.17) * u); }
  s += poly(pts([cx - w / 2 - 6, G, cx - w / 2 + 6, G, cx - w * 0.17 + 5, top, cx - w * 0.17 - 5, top]), f);
  s += poly(pts([cx + w / 2 + 6, G, cx + w / 2 - 6, G, cx + w * 0.17 - 5, top, cx + w * 0.17 + 5, top]), f);
  s += loop(7, function (i) {                                        // one X per bay, tightening upward
    var u0 = i / 7, u1 = (i + 1) / 7, ya = G - h * u0, yb = G - h * u1;
    return ln(legX(-1, u0), ya, legX(1, u1), yb, f, 3.2, 0.95) +
      ln(legX(1, u0), ya, legX(-1, u1), yb, f, 3.2, 0.95) +
      ln(legX(-1, u1), yb, legX(1, u1), yb, f, 3.2, 0.95);
  });
  bx0 = cx + brace * w * 0.22; by0 = top + h * 0.05;
  bx1 = cx + brace * (w * 0.55 + h * 0.46); by1 = G;
  s += poly(pts([bx0 - 7, by0, bx0 + 7, by0, bx1 + 10, by1, bx1 - 10, by1]), f);
  s += loop(5, function (k) {                                        // ties, level with the main frame
    var u = 0.17 + k * 0.17;
    return ln(bx0 + (bx1 - bx0) * (1 - u), by0 + (by1 - by0) * (1 - u), legX(brace, u), G - h * u, f, 2.8, 0.85);
  });
  s += poly(pts([cx - w * 0.46, G - h * 0.21, cx + w * 0.46, G - h * 0.21, cx + w * 0.27, G - h * 0.04, cx - w * 0.27, G - h * 0.04]), f);
  s += rect(cx - w * 0.52, G - h * 0.235, w * 1.04, h * 0.03 + 4, f);
  s += rect(cx - w * 0.38, top - 11, w * 0.76, 13, f);
  s += '<circle cx="' + nn(cx) + '" cy="' + nn(sy) + '" r="' + nn(sr) + '" fill="none" stroke="' + f + '" stroke-width="8"/>';
  s += loop(6, function (k) { var a = k * Math.PI / 6; return ln(cx - Math.cos(a) * sr, sy - Math.sin(a) * sr, cx + Math.cos(a) * sr, sy + Math.sin(a) * sr, f, 3, 0.9); });
  s += circ(cx, sy, sr * 0.24, f);
  s += '<circle cx="' + nn(cx) + '" cy="' + nn(sy) + '" r="' + nn(sr) + '" fill="none" stroke="' + rim + '" stroke-width="2.6" opacity="' + C.rimOp + '"/>';
  s += poly(pts([legX(1, 0) + 6, G, legX(1, 0) + 2, G, legX(1, 1) - 1, top, legX(1, 1) + 3, top]), rim, ' opacity="' + C.rimOp + '"');
  return s + circ(cx, sy - sr - 9, 3.6, AMBER, ' opacity="0.75"');
}
/* Site floodlight mast — the mine's answer to `bigLamp`. The city
   scenes buy their scale jump from a street lamp; a pit has no streets,
   so the same job falls to a lattice stick with a head of four lamps. */
function floodMast(x, h, f, rim) {
  var top = G - h, s = rect(x - 4.5, top + 12, 9, h - 12, f);
  s += loop(9, function (i) {
    var y0 = G - (h - 12) * i / 9, y1 = G - (h - 12) * (i + 1) / 9;
    return ln(x - 4.5, y0, x + 4.5, y1, f, 2, 0.9) + ln(x + 4.5, y0, x - 4.5, y1, f, 2, 0.9);
  });
  s += rect(x - 36, top, 72, 9, f);
  s += loop(4, function (i) {
    var lx = x - 27 + i * 18;
    return poly(pts([lx - 8, top + 8, lx + 8, top + 8, lx + 6, top + 21, lx - 6, top + 21]), f) +
      circ(lx, top + 22, 5, AMBER, ' opacity="0.7"') + circ(lx, top + 22, 24, AMBER, ' opacity="0.08"');
  });
  return s + rect(x + 1.5, top + 12, 3, h - 12, rim, ' opacity="0.22"');
}

/* ==================================================================
   6. Region configuration + composition
   ================================================================== */
/* Ten times of day on the same gold afternoon. Each region is a
   variation WITHIN the gold family, not a different hue: the ink is
   always a deep amber-brown, the horizon always burnished gold, and
   the sun always low and right of x=800.
     us     hard bright gold      eu     cooler brass
     iran   ochre and rose        uk     hazier smoke-gold
     china  red-gold              japan  pink-gold
     global neutral bronze        india  saffron into rose
     gold   cold ink, hot gold    em     green-gold
   `gold` is the one deliberate break: its ink is the only cold one in
   the file. That is the point of the slide — a cold grey silhouette
   against the hottest horizon of the set is what makes the scene read
   as metal rather than as another dusk over another city.            */
var CFG = {
  us:     { ink: '#160D04', hz: '#E4A526', sun: '#FFF0BE', sunX: 1250, sunY: 682, rimOp: 0.52 },
  iran:   { ink: '#1A0C08', hz: '#CE8134', sun: '#FFCE8E', sunX: 1218, sunY: 702, rimOp: 0.54 },
  china:  { ink: '#180703', hz: '#C25518', sun: '#FFB552', sunX: 1180, sunY: 716, rimOp: 0.50 },
  eu:     { ink: '#120F06', hz: '#AE9838', sun: '#F6EBAE', sunX: 1272, sunY: 692, rimOp: 0.46 },
  /* uk's terrace runs unbroken across the near layer (rooflines at
     y=588..648), so its sun clears them and veils itself in cloud */
  uk:     { ink: '#151109', hz: '#A08A56', sun: '#EDDCAC', sunX: 1200, sunY: 566, rimOp: 0.34 },
  /* japan's sun is framed in the torii opening (x 1000..1300) and sits
     just above Fuji's slope, which passes y=625 at this x */
  japan:  { ink: '#190A0B', hz: '#DA8E68', sun: '#FFD8B4', sunX: 1156, sunY: 556, rimOp: 0.48 },
  /* global's sun sits inside the wireframe globe, left of the near
     block that starts at x=1288 and clear of the parapet at y=730 */
  global: { ink: '#120E07', hz: '#B4893E', sun: '#F7DFA6', sunX: 1230, sunY: 656, rimOp: 0.40 },
  /* india's sun clears the Gateway, which ends at x=1170, and sits to
     its right so the arch is read against the bloom rather than on it */
  india:  { ink: '#1A0908', hz: '#D0683A', sun: '#FFCE93', sunX: 1252, sunY: 700, rimOp: 0.52 },
  /* gold's sun is the hardest and smallest in the file — a small disc
     at high opacity, not a soft ball — because a mine at this hour is
     lit like a spotlight and everything on site is cut steel */
  gold:   { ink: '#0B0E13', hz: '#F0B22A', sun: '#FFF8DC', sunX: 1236, sunY: 712, rimOp: 0.62 },
  /* em's sun rides higher than global's: the near layer is open plain
     rather than a parapet, so nothing is there to hide a low disc */
  em:     { ink: '#0E1009', hz: '#96A04A', sun: '#F2ECB4', sunX: 1252, sunY: 664, rimOp: 0.42 }
};
/* Dark warm top, burnished middle, hot core at the horizon (~84%,
   which is where the page's ground band starts, so the gold has to
   arrive well before it — by 46% the sky is already carrying colour). */
function skyOf(c) {
  return c.skyStops || [mix(c.ink, '#060301', 0.5) + ' 0%', mix(c.ink, c.hz, 0.07) + ' 18%', mix(c.ink, c.hz, 0.32) + ' 46%',
    mix(c.ink, c.hz, 0.66) + ' 68%', mix(c.ink, c.hz, 0.94) + ' 84%', mix(c.hz, c.sun, 0.35) + ' 100%'];
}
CFG.japan.skyStops = ['#0B0406 0%', '#26100F 18%', '#653024 46%', '#AE6042 68%', '#D68E68 84%', '#F4BC94 100%'];
/* India is the only sky with a genuine hue SHIFT down it: plum at the
   top, rose through the middle, saffron at the horizon. The default
   ramp only mixes ink toward hz, which would have landed on the same
   burnt orange china already owns, and two regions with the same sky
   defeat the point of having a sky per region. */
CFG.india.skyStops = ['#0D0407 0%', '#2C0E15 18%', '#70292E 46%', '#B85446 68%', '#D9803F 84%', '#F8C88C 100%'];

var BUILD = {

  /* ---- UNITED STATES — Midtown Manhattan, hard bright gold ------- */
  us: function (P, c) {
    return {
      far: candleWall(2011, P.cUp, P.cDn, 1.0) +
        clouds(1107, 7, mix(c.hz, BONE, 0.2), 300, 560, 0.16) +
        sunCore('us-sun', c.sunX, c.sunY, 46, mix(c.sun, BONE, 0.3), c.sun, 0.64) +
        cityBand(-160, 1740, P.dist, 2101, { wmin: 46, wmax: 96, hmin: 34, hmax: 96 }) +
        cityBand(-160, 1740, P.far, 2203, { wmin: 52, wmax: 112, hmin: 70, hmax: 200 }) +
        bloom('us-bleed', c.sunX, c.sunY, 300, c.sun, 0.24) +
        haze('us-h1', c.hz, 400, 0.86) + shade('us-sh', c.ink, 0.74),
      mid: cityBand(-160, 660, P.mid, 3301, { wmin: 64, wmax: 126, hmin: 110, hmax: 250 }) +
        cityBand(1040, 1740, P.mid, 3307, { wmin: 68, wmax: 138, hmin: 120, hmax: 250 }) +
        tower(636, 122, 306, P.mid, 3311, { crown: 'mech', setbacks: 1 }) +
        chrysler(1006, 400, P.mid) +
        empireState(846, 476, P.mid) +
        haze('us-h2', c.hz, 566, 0.32),
      near: (function () {
        var f = P.near.fill, rim = P.near.rim;
        return nearBlock(-160, 402, 198, P.near, 3411, 'mech') + waterTower(18, G - 198, 2.0, f, rim) + waterTower(172, G - 198, 1.5, f, rim) +
          nearBlock(266, 212, 136, P.near, 3413) + waterTower(316, G - 136, 1.25, f, rim) +
          nearBlock(940, 206, 176, P.near, 3415, 'mech') + waterTower(986, G - 176, 1.4, f, rim) +
          nearBlock(1434, 320, 252, P.near, 3417) + waterTower(1492, G - 252, 2.2, f, rim) +
          parapet(730, f, rim) + balusters(664, 730, f, rim, 62, 14) +
          bigLamp(1090, 168, f, rim) + haze('us-h3', c.hz, 640, 0.10) +
          floorPlate('us-fl', c.sunX, P.near, c.sun, 2411);
      })()
    };
  },

  /* ---- IRAN — Tehran/Isfahan silhouette, ochre and rose ---------- */
  iran: function (P, c) {
    var motif = loop(24, function (i) {
      var mx = 90 + (i % 8) * 200, my = 90 + Math.floor(i / 8) * 190;
      return '<polygon points="' + star(mx, my, 44, 8, 0) + '" fill="none" stroke="' + BONE + '" stroke-width="1.3" opacity="0.05"/>';
    });
    return {
      far: candleWall(4011, P.cUp, P.cDn, 0.92) + motif +
        clouds(4101, 7, mix(c.hz, BONE, 0.2), 340, 600, 0.16) +
        sunCore('iran-sun', c.sunX, c.sunY, 48, mix(c.sun, BONE, 0.22), c.sun, 0.6) +
        cityBand(-160, 1740, P.dist, 4103, { wmin: 70, wmax: 150, hmin: 22, hmax: 62 }) +
        cityBand(-160, 1740, P.far, 4107, { wmin: 60, wmax: 140, hmin: 44, hmax: 130 }) +
        bloom('iran-bleed', c.sunX, c.sunY, 320, c.sun, 0.24) +
        haze('iran-h1', c.hz, 400, 0.88) + shade('iran-sh', c.ink, 0.74),
      mid: cityBand(-160, 430, P.mid, 4201, { wmin: 76, wmax: 150, hmin: 46, hmax: 120 }) +
        cityBand(1250, 1740, P.mid, 4207, { wmin: 76, wmax: 150, hmin: 46, hmax: 130 }) +
        (function () {
          var f = P.mid.fill, s = '';
          s += rect(500, G - 108, 300, 108, f) + loop(4, function (i) { return pathd('M' + (520 + i * 68) + ' ' + G + ' L' + ogive(520 + i * 68, 40, G - 60, G - 92).slice(1) + ' L' + (560 + i * 68) + ' ' + G + ' Z', AMBER, ' opacity="0.12"'); });
          s += iwan(608, 224, 322, P.mid);
          s += rect(742, G - 196, 232, 196, f) + winGrid(742, G - 196, 232, 196, 4211, P.mid);
          s += pathd(onion(858, G - 196, 204, 224), f) + rect(858 - 102, G - 200, 204, 6, P.mid.rim, ' opacity="0.3"');
          s += rect(854, G - 448, 9, 40, f) + circ(858, G - 454, 7, AMBER, ' opacity="0.6"');
          s += rect(858 + 60, G - 380, 4, 150, P.mid.rim, ' opacity="0.3"');
          s += pathd(onion(1046, G - 104, 116, 122), f) + rect(1000, G - 104, 92, 104, f);
          s += minaret(700, 430, P.mid) + minaret(1108, 412, P.mid);
          return s;
        })() + haze('iran-h2', c.hz, 560, 0.33),
      near: (function () {
        var f = P.near.fill, rim = P.near.rim, wall = 'M-140 ' + G + ' L-140 ' + (G - 128) + ' L560 ' + (G - 128) + ' L560 ' + G + ' Z';
        wall += loop(5, function (i) { return ' M' + (-80 + i * 128) + ' ' + G + ' L' + ogive(-80 + i * 128, 62, G - 46, G - 104).slice(1) + ' L' + (-18 + i * 128) + ' ' + G + ' Z'; });
        return pathd(wall, f, ' fill-rule="evenodd"') + rect(-140, G - 137, 700, 11, f) +
          palm(1436, 560, f, 4301, 1.8) + palm(1256, 300, f, 4307, 1.1) + palm(760, 224, f, 4311, 0.8) +
          scrub(4317, 10, f, 560, 1740) + grass(4321, 26, f, 520, 1740) +
          bigLamp(960, 250, f, rim) + haze('iran-h3', c.hz, 640, 0.10) +
          floorPlate('iran-fl', c.sunX, P.near, c.sun, 4411);
      })()
    };
  },

  /* ---- CHINA — Beijing/Shanghai, red-gold ----------------------- */
  china: function (P, c) {
    return {
      far: candleWall(5011, P.cUp, P.cDn, 0.95) +
        clouds(5101, 8, mix(c.hz, BONE, 0.2), 300, 580, 0.16) +
        sunCore('china-sun', c.sunX, c.sunY, 50, mix(c.sun, BONE, 0.2), c.sun, 0.62) +
        cityBand(-160, 1740, P.dist, 5103, { wmin: 50, wmax: 108, hmin: 34, hmax: 104 }) +
        cityBand(-160, 1740, P.far, 5107, { wmin: 54, wmax: 122, hmin: 66, hmax: 196 }) +
        bloom('china-bleed', c.sunX, c.sunY, 330, c.sun, 0.26) +
        haze('china-h1', c.hz, 400, 0.88) + shade('china-sh', c.ink, 0.74),
      mid: cityBand(-160, 320, P.mid, 5201, { wmin: 66, wmax: 128, hmin: 90, hmax: 220 }) +
        cityBand(640, 1080, P.mid, 5205, { wmin: 66, wmax: 128, hmin: 120, hmax: 268 }) +
        cityBand(1400, 1740, P.mid, 5209, { wmin: 66, wmax: 128, hmin: 90, hmax: 230 }) +
        pagoda(470, 226, 7, 52, P.mid) +
        pearlTower(1242, 452, P.mid) +
        haze('china-h2', c.hz, 560, 0.33),
      near: (function () {
        var f = P.near.fill, rim = P.near.rim;
        return bloom('china-lantern', 0, -400, 1, AMBER, 0.34) +
          nearBlock(-160, 322, 152, P.near, 5311, 'mech') + nearBlock(1476, 264, 178, P.near, 5313) +
          gate(816, 470, 300, P.near) +
          lanternRow(30, 812, 1540, 4, f, 'china-lantern', 1.15) +
          parapet(732, f, rim) + scrub(5301, 8, f, -120, 1720) +
          haze('china-h3', c.hz, 650, 0.10) +
          floorPlate('china-fl', c.sunX, P.near, c.sun, 5411);
      })()
    };
  },

  /* ---- EURO AREA — Frankfurt, cooler brass ---------------------- */
  eu: function (P, c) {
    var ring = loop(12, function (i) {
      var a = -Math.PI / 2 + i * Math.PI / 6;
      return '<polygon points="' + star(1178 + Math.cos(a) * 138, 248 + Math.sin(a) * 138, 19) + '" fill="' + mix(AMBER, BONE, 0.35) + '" opacity="0.82"/>';
    });
    return {
      far: candleWall(6011, P.cUp, P.cDn, 0.9) +
        clouds(6103, 6, mix(c.hz, BONE, 0.2), 380, 580, 0.14) +
        sunCore('eu-sun', c.sunX, c.sunY, 44, mix(c.sun, BONE, 0.35), c.sun, 0.58) + ring +
        cityBand(-160, 1740, P.dist, 6105, { wmin: 48, wmax: 104, hmin: 30, hmax: 96 }) +
        cityBand(-160, 1740, P.far, 6109, { wmin: 54, wmax: 118, hmin: 62, hmax: 180 }) +
        bloom('eu-bleed', c.sunX, c.sunY, 290, c.sun, 0.22) +
        haze('eu-h1', c.hz, 400, 0.86) + shade('eu-sh', c.ink, 0.74),
      mid: cityBand(-160, 1740, P.mid, 6201, { wmin: 70, wmax: 150, hmin: 74, hmax: 168 }) +
        tower(150, 128, 386, P.mid, 6211, { crown: 'spire', setbacks: 1, piers: true }) +
        tower(408, 108, 320, P.mid, 6213, { crown: 'flat', setbacks: 0 }) +
        tower(524, 108, 356, P.mid, 6215, { crown: 'flat', setbacks: 0 }) +
        messeturm(960, 470, P.mid) +
        tower(1330, 120, 300, P.mid, 6219, { crown: 'mech', setbacks: 1 }) +
        haze('eu-h2', c.hz, 566, 0.32),
      near: (function () {
        var f = P.near.fill, rim = P.near.rim;
        return colonnade(880, 700, 300, 7, f, rim) +
          nearBlock(-160, 352, 172, P.near, 6311, 'mech') + nearBlock(196, 178, 112, P.near, 6313) +
          parapet(730, f, rim) + balusters(660, 730, f, rim, 58, 15) +
          bigLamp(792, 198, f, rim) + haze('eu-h3', c.hz, 640, 0.10) +
          floorPlate('eu-fl', c.sunX, P.near, c.sun, 6411);
      })()
    };
  },

  /* ---- UNITED KINGDOM — London, hazy smoke-gold, drizzle -------- */
  uk: function (P, c) {
    return {
      far: candleWall(7011, P.cUp, P.cDn, 0.82) +
        sunCore('uk-sun', c.sunX, c.sunY, 46, mix(c.sun, BONE, 0.4), c.sun, 0.5) +
        clouds(7101, 15, mix(c.hz, BONE, 0.22), 120, 560, 0.19) +
        cityBand(-160, 1740, P.dist, 7103, { wmin: 62, wmax: 140, hmin: 20, hmax: 66 }) +
        cityBand(-160, 1740, P.far, 7107, { wmin: 66, wmax: 150, hmin: 40, hmax: 128 }) +
        bloom('uk-bleed', c.sunX, c.sunY, 340, c.sun, 0.2) +
        haze('uk-h1', c.hz, 380, 0.9) + shade('uk-sh', c.ink, 0.72),
      mid: cityBand(-160, 1740, P.mid, 7201, { wmin: 76, wmax: 156, hmin: 48, hmax: 120 }) +
        '<defs><radialGradient id="uk-clock"><stop offset="0" stop-color="' + AMBER + '" stop-opacity="0.6"/><stop offset="1" stop-color="' + AMBER + '" stop-opacity="0"/></radialGradient></defs>' +
        tower(1024, 132, 210, P.mid, 7205, { crown: 'mech', setbacks: 1 }) +
        gherkin(886, 322, P.mid, 'uk-gherkin') +
        shard(1352, 470, P.mid) +
        elizabethTower(438, 420, P.mid, 'uk-clock') +
        haze('uk-h2', c.hz, 560, 0.36),
      near: (function () {
        var f = P.near.fill, rim = P.near.rim;
        return loop(11, function (i) {
          var x = -160 + i * 172, hh = 112 + (i % 3) * 30;
          return rect(x, G - hh, 176, hh, f) + rect(x, G - hh - 8, 176, 9, f) +
            rect(x + 26, G - hh - 34, 22, 28, f) + rect(x + 128, G - hh - 30, 20, 24, f);
        }) + drizzle(7301, 190, mix(c.sun, BONE, 0.3)) +
          parapet(732, f, rim) + balusters(672, 732, f, rim, 52, 12) +
          bigLamp(1240, 150, f, rim) + haze('uk-h3', c.hz, 650, 0.10) +
          floorPlate('uk-fl', c.sunX, P.near, c.sun, 7411);
      })()
    };
  },

  /* ---- JAPAN — Fuji, torii, pink-gold --------------------------- */
  japan: function (P, c) {
    var rays = loop(17, function (i) {                               // fan up and left, off the low sun
      var a = Math.PI + i * Math.PI / 16;
      return ln(c.sunX, c.sunY, c.sunX + Math.cos(a) * 1000, c.sunY + Math.sin(a) * 1000, c.sun, 26, i % 2 ? 0.03 : 0.06);
    });
    return {
      far: candleWall(8011, P.cUp, P.cDn, 0.86) + rays +
        sunCore('japan-sun', c.sunX, c.sunY, 54, mix(c.sun, BONE, 0.3), c.sun, 0.6) +
        clouds(8101, 7, mix(c.hz, BONE, 0.24), 250, 500, 0.16) +
        fuji(930, 620, 252, P.far) + snowCap(930, G - 252, 46, 152, 58, mix(BONE, c.sun, 0.35), 8107) +
        cityBand(-160, 1740, P.dist, 8109, { wmin: 60, wmax: 130, hmin: 16, hmax: 48 }) +
        bloom('japan-bleed', c.sunX, c.sunY, 300, c.sun, 0.2) +
        haze('japan-h1', c.hz, 420, 0.84) + shade('japan-sh', c.ink, 0.74),
      mid: cityBand(-160, 1740, P.mid, 8201, { wmin: 80, wmax: 170, hmin: 30, hmax: 78 }) +
        loop(10, function (i) { return elli(-100 + i * 196, G - 6, 66, 50, mix(P.mid.fill, P.mid.haze, 0.1)); }) +
        pagoda(324, 190, 5, 50, P.mid, true) +
        (function () { var f = P.mid.fill; return rect(596, G - 96, 176, 96, f) + eaves(684, G - 96, 250, 66, f) + rect(1452, G - 84, 150, 84, f) + eaves(1527, G - 84, 216, 58, f); })() +
        haze('japan-h2', c.hz, 566, 0.32),
      near: (function () {
        var f = P.near.fill, rim = P.near.rim;
        return torii(1156, 340, 372, f, rim) +
          rect(408, G - 92, 40, 92, f) + rect(388, G - 118, 80, 28, f) + poly(pts([378, G - 118, 428, G - 160, 478, G - 118]), f) +
          circ(428, G - 104, 8, AMBER, ' opacity="0.5"') + circ(428, G - 104, 30, AMBER, ' opacity="0.07"') +
          rect(-140, G - 118, 260, 118, f) +
          pineBranch(1680, -70, 1090, 262, f, 8301) +
          scrub(8305, 12, f, -120, 1740) + grass(8309, 46, f, -120, 1740) +
          haze('japan-h3', c.hz, 660, 0.10) +
          floorPlate('japan-fl', c.sunX, P.near, c.sun, 8411);
      })()
    };
  },

  /* ---- GLOBAL — anonymous cross-asset skyline, neutral bronze --- */
  global: function (P, c) {
    return {
      far: candleWall(9011, P.cUp, P.cDn, 1.0) + stars(9101, 70, 260) +
        clouds(9103, 6, mix(c.hz, BONE, 0.2), 300, 560, 0.15) +
        sunCore('global-sun', c.sunX, c.sunY, 46, mix(c.sun, BONE, 0.35), c.sun, 0.6) +
        globe(1206, 622, 196, 'global-clip', mix(c.sun, BONE, 0.25)) +
        cityBand(-160, 1740, P.dist, 9105, { wmin: 48, wmax: 104, hmin: 30, hmax: 94 }) +
        cityBand(-160, 1740, P.far, 9109, { wmin: 54, wmax: 120, hmin: 62, hmax: 186 }) +
        bloom('global-bleed', c.sunX, c.sunY, 290, c.sun, 0.22) +
        haze('global-h1', c.hz, 400, 0.86) + shade('global-sh', c.ink, 0.74),
      mid: cityBand(-160, 1740, P.mid, 9201, { wmin: 62, wmax: 140, hmin: 84, hmax: 210 }) +
        tower(276, 112, 348, P.mid, 9211, { crown: 'spire', setbacks: 2 }) +
        tower(726, 132, 296, P.mid, 9213, { crown: 'step', setbacks: 1 }) +
        tower(1436, 118, 374, P.mid, 9215, { crown: 'pitch', setbacks: 1 }) +
        haze('global-h2', c.hz, 566, 0.32),
      near: (function () {
        var f = P.near.fill, rim = P.near.rim;
        return nearBlock(-160, 350, 198, P.near, 9311, 'mech') + nearBlock(226, 194, 126, P.near, 9313) +
          nearBlock(1288, 196, 170, P.near, 9315) + nearBlock(1508, 232, 238, P.near, 9317, 'mech') +
          rect(288, G - 300, 5, 112, f) +
          parapet(730, f, rim) + balusters(664, 730, f, rim, 60, 13) +
          bigLamp(1030, 176, f, rim) + haze('global-h3', c.hz, 640, 0.10) +
          floorPlate('global-fl', c.sunX, P.near, c.sun, 9411);
      })()
    };
  },

  /* ---- INDIA — Mumbai at dusk, saffron into rose ---------------- */
  /* Three ages of the city stacked by depth, which is how Mumbai
     actually presents itself from the harbour: colonial stone in
     front, the BKC slabs behind it, and the low sprawl behind that. */
  india: function (P, c) {
    return {
      far: candleWall(10011, P.cUp, P.cDn, 0.94) +
        /* Fewer, weaker clouds than the other bright regions get. This
           sky is the most saturated in the file, so a stratus bar at
           the usual 0.18 stops being atmosphere and starts being a
           hard grey lens sitting on top of the rose. */
        clouds(10101, 7, mix(c.hz, BONE, 0.1), 250, 540, 0.11) +
        sunCore('india-sun', c.sunX, c.sunY, 50, mix(c.sun, BONE, 0.24), c.sun, 0.62) +
        cityBand(-160, 1740, P.dist, 10103, { wmin: 54, wmax: 118, hmin: 24, hmax: 76 }) +
        cityBand(-160, 1740, P.far, 10107, { wmin: 58, wmax: 128, hmin: 52, hmax: 166 }) +
        bloom('india-bleed', c.sunX, c.sunY, 330, c.sun, 0.26) +
        haze('india-h1', c.hz, 400, 0.88) + shade('india-sh', c.ink, 0.74),
      /* The left band is kept to chawl height on purpose: the copy sits
         over it, and a 200-unit tower under the headline is the one
         thing this deck will not forgive. The district starts at 560. */
      mid: cityBand(-160, 560, P.mid, 10201, { wmin: 84, wmax: 172, hmin: 38, hmax: 94 }) +
        cityBand(560, 1740, P.mid, 10205, { wmin: 66, wmax: 142, hmin: 88, hmax: 206 }) +
        tower(628, 140, 258, P.mid, 10211, { setbacks: 0, crown: 'flat', piers: true }) +
        tower(796, 118, 322, P.mid, 10213, { setbacks: 1, crown: 'mech' }) +
        tower(1494, 106, 218, P.mid, 10215, { setbacks: 0, crown: 'flat' }) +
        (function () {                                               // a domed colonial block, chhatris on the corners
          var f = P.mid.fill, s = rect(1330, G - 150, 218, 150, f) + winGrid(1330, G - 150, 218, 150, 10217, P.mid);
          s += rect(1322, G - 160, 234, 11, f) + rect(1322, G - 161, 234, 3, P.mid.rim, ' opacity="0.28"');
          s += rect(1410, G - 178, 58, 20, f) + pathd(dome(1439, G - 178, 74, 84), f);
          s += rect(1437, G - 274, 4, 20, f);
          s += chhatri(1348, G - 160, 34, 62, f) + chhatri(1530, G - 160, 34, 62, f);
          return s + rect(1545, G - 150, 3, 150, P.mid.rim, ' opacity="' + P.mid.rimOp + '"');
        })() +
        haze('india-h2', c.hz, 560, 0.33),
      near: (function () {
        var f = P.near.fill, rim = P.near.rim;
        return rect(-140, G - 124, 780, 124, f) + rect(-140, G - 136, 780, 13, f) +   // the harbour promenade wall
          rect(-140, G - 137, 780, 3, rim, ' opacity="0.24"') +
          /* The lamp string along the sea wall instead of the single
             oversized `bigLamp` the city scenes use. A lamp that size
             would land at 45% of the frame, right on the edge of the
             copy column, and it would be the tallest thing left of the
             Gateway — which is exactly backwards. A low row also says
             Marine Drive, which one lamp never would. */
          loop(6, function (i) {
            var x = -60 + i * 156, hh = 96 - i * 4;
            return rect(x - 3.5, G - 136 - hh, 7, hh, f) +
              rect(x - 13, G - 136 - hh - 7, 26, 8, f) +
              circ(x, G - 136 - hh - 2, 7, AMBER, ' opacity="0.55"') +
              circ(x, G - 136 - hh - 2, 30, AMBER, ' opacity="0.07"');
          }) +
          gateway(1014, 322, 318, P.near) +
          palm(1388, 302, f, 10301, 1.2) + palm(1530, 228, f, 10307, 0.95) + palm(830, 196, f, 10311, 0.78) +
          scrub(10317, 9, f, 700, 1740) + grass(10321, 24, f, 660, 1740) +
          haze('india-h3', c.hz, 636, 0.15) +                        // harbour damp: the thickest h3 in the set
          floorPlate('india-fl', c.sunX, P.near, c.sun, 10411);
      })()
    };
  },

  /* ---- GOLD MINERS — headframe and open pit, cold ink, hot gold -- */
  /* The only scene with no city in it at all. Everything that a city
     region gets from massing, this one has to get from the light: one
     small hard sun, cut rock in stacked lit edges, and open steel that
     the bloom comes straight through. */
  gold: function (P, c) {
    return {
      far: candleWall(11011, P.cUp, P.cDn, 1.0) +
        clouds(11101, 4, mix(c.hz, BONE, 0.18), 280, 520, 0.11) +    // desert air: barely any cloud
        sunCore('gold-sun', c.sunX, c.sunY, 40, mix(c.sun, BONE, 0.5), c.sun, 0.76) +
        ridge(11103, P.dist, 34, 96, -180, 1760, 88) +
        ridge(11107, P.far, 16, 74, -180, 1760, 64) +
        (function () {                                               // the smelter, far enough off to be a smudge
          var f = P.far.fill, s = rect(1486, G - 176, 13, 176, f) + rect(1522, G - 148, 11, 148, f);
          return s + rect(1452, G - 84, 108, 84, f) + rect(1486, G - 176, 3, 176, P.far.rim, ' opacity="' + P.far.rimOp + '"');
        })() +
        bloom('gold-bleed', c.sunX, c.sunY, 300, c.sun, 0.28) +
        haze('gold-h1', c.hz, 400, 0.86) + shade('gold-sh', c.ink, 0.74),
      /* The pit leans right, away from the copy, and the gantry climbs
         straight across the disc — open truss, so the sun is striped
         rather than blocked. That stripe is the whole image. */
      mid: benches(430, 300, G - 128, 4, wash(P.mid, 0.34, c), 11201, 9) +
        benches(1436, 342, G - 212, 5, P.mid, 11205, -14) +
        conveyor(1148, 748, 1500, 606, P.mid) +
        (function () {                                               // the mill the gantry feeds
          /* Three tall lit slots rather than `winGrid`: a mill has one
             open charging floor, not twenty storeys of desks, and the
             office grid was the one thing in the frame that made this
             look like another city after all. */
          var f = P.mid.fill, s = rect(1450, G - 190, 158, 190, f);
          s += loop(3, function (i) { return rect(1470 + i * 42, G - 150, 22, 104, AMBER, ' opacity="' + (0.13 + i * 0.03).toFixed(2) + '"'); });
          return s + rect(1442, G - 200, 174, 12, f) + roofPlant(1450, G - 190, 158, 11211, f, P.mid.rim);
        })() +
        haze('gold-h2', c.hz, 560, 0.34),
      near: (function () {
        var f = P.near.fill, rim = P.near.rim;
        return bank(11301, P.near, -180, 830, 40, 74, 58) + scrub(11303, 7, f, -140, 700) +
          headframe(1002, 438, P.near, 11305, -1) +
          rect(880, G - 104, 118, 104, f) + rect(872, G - 114, 134, 11, f) +      // the hoist house at its foot
          floodMast(1548, 306, f, rim) +
          scrub(11311, 15, f, 620, 1740) +                           // loose rock, and no `grass`: nothing grows here
          haze('gold-h3', c.hz, 648, 0.10) +
          floorPlate('gold-fl', c.sunX, P.near, c.sun, 11411);
      })()
    };
  },

  /* ---- EMERGING MARKETS — several cities at once, green-gold ----- */
  /* `global` is one skyline standing for everything; EM is the opposite
     idea and has to look it. Six bands over DISJOINT x windows, each in
     its own wash, so the gaps between clusters are visible and the eye
     counts cities instead of reading one wall. */
  em: function (P, c) {
    var d2 = wash(P.far, 0.30, c), m2 = wash(P.mid, 0.42, c);
    return {
      far: candleWall(12011, P.cUp, P.cDn, 1.0) + stars(12101, 54, 230) +
        clouds(12103, 6, mix(c.hz, BONE, 0.2), 290, 550, 0.15) +
        sunCore('em-sun', c.sunX, c.sunY, 46, mix(c.sun, BONE, 0.32), c.sun, 0.6) +
        cityBand(-160, 1740, P.dist, 12105, { wmin: 44, wmax: 98, hmin: 18, hmax: 66 }) +
        cityBand(300, 900, d2, 12107, { wmin: 50, wmax: 106, hmin: 58, hmax: 148 }) +
        cityBand(1120, 1740, d2, 12109, { wmin: 50, wmax: 106, hmin: 68, hmax: 176 }) +
        cityBand(-160, 500, P.far, 12111, { wmin: 56, wmax: 122, hmin: 44, hmax: 124 }) +
        cityBand(880, 1400, P.far, 12113, { wmin: 56, wmax: 122, hmin: 56, hmax: 162 }) +
        bloom('em-bleed', c.sunX, c.sunY, 290, c.sun, 0.23) +
        haze('em-h1', c.hz, 400, 0.86) + shade('em-sh', c.ink, 0.74),
      /* The gap from 1060 to 1360 is the sun's, and it gets a washed,
         deliberately low cluster: something nearer than the sun but
         under it, which is what sells the distance behind it. */
      mid: cityBand(-160, 470, P.mid, 12201, { wmin: 62, wmax: 134, hmin: 54, hmax: 122 }) +
        cityBand(620, 1060, P.mid, 12205, { wmin: 66, wmax: 142, hmin: 118, hmax: 262 }) +
        cityBand(1060, 1360, m2, 12207, { wmin: 70, wmax: 152, hmin: 34, hmax: 84 }) +
        cityBand(1360, 1740, P.mid, 12209, { wmin: 66, wmax: 142, hmin: 98, hmax: 228 }) +
        tower(884, 126, 344, P.mid, 12211, { crown: 'spire', setbacks: 2 }) +
        tower(1456, 114, 296, P.mid, 12213, { crown: 'mech', setbacks: 1 }) +
        haze('em-h2', c.hz, 566, 0.32),
      near: (function () {
        var f = P.near.fill, rim = P.near.rim;
        return elli(280, G + 22, 760, 50, f) + elli(1240, G + 18, 680, 42, f) +   // open ground, not a plaza
          elli(760, G + 26, 420, 34, f) +
          loop(7, function (i) {                                     // a line of masts walking into the distance
            var x = 690 + i * 126, hh = 168 - i * 19;
            return rect(x, G - hh, 4.5, hh, f) + rect(x - 11, G - hh, 27, 4, f) +
              circ(x + 2, G - hh - 5, 3, AMBER, ' opacity="0.5"');
          }) +
          loop(26, function (i) {                                    // a slack wire fence along the plain
            var x = -150 + i * 74;
            return rect(x, G - 34, 3.5, 36, f);
          }) +
          ln(-150, G - 32, 1760, G - 28, f, 2.2, 0.85) + ln(-150, G - 18, 1760, G - 15, f, 2.2, 0.85) +
          scrub(12301, 13, f, -140, 1740) + grass(12305, 40, f, -140, 1740) +
          haze('em-h3', c.hz, 640, 0.10) +
          floorPlate('em-fl', c.sunX, P.near, c.sun, 12411);
      })()
    };
  }
};

/* ==================================================================
   7. Public metadata + renderer
   ================================================================== */
var SCENES = {
  us:     { name: 'United States',  badge: 'US · WASHINGTON',       tint: '#F2C44C', sky: skyOf(CFG.us) },
  iran:   { name: 'Iran',           badge: 'IRAN · TEHRAN',         tint: '#E29A52', sky: skyOf(CFG.iran) },
  china:  { name: 'China',          badge: 'CHINA · BEIJING',       tint: '#E2742E', sky: skyOf(CFG.china) },
  eu:     { name: 'Euro Area',      badge: 'EURO AREA · FRANKFURT', tint: '#D6C468', sky: skyOf(CFG.eu) },
  uk:     { name: 'United Kingdom', badge: 'UK · LONDON',           tint: '#C6B283', sky: skyOf(CFG.uk) },
  japan:  { name: 'Japan',          badge: 'JAPAN · TOKYO',         tint: '#EFA57E', sky: skyOf(CFG.japan) },
  global: { name: 'Global',         badge: 'GLOBAL · CROSS-ASSET',  tint: '#D4A758', sky: skyOf(CFG.global) },
  india:  { name: 'India',          badge: 'INDIA · MUMBAI',        tint: '#E4734F', sky: skyOf(CFG.india) },
  gold:   { name: 'Gold miners',    badge: 'GOLD · THE MINERS',     tint: '#F5C63A', sky: skyOf(CFG.gold) },
  em:     { name: 'Emerging markets', badge: 'EM · CROSS-MARKET',   tint: '#B9B45C', sky: skyOf(CFG.em) }
};

function layerHTML(cls, depth, inner) {
  return '<div class="layer ' + cls + '" style="--depth:' + depth + '">' +
    '<svg viewBox="0 0 1600 900" preserveAspectRatio="xMidYMax slice">' + inner + '</svg></div>';
}
function sceneHTML(region) {
  var key = SCENES[region] ? region : 'global', c = CFG[key], L = BUILD[key](palette(c), c), k = hx(c.ink).join(',');
  /* Two stacked backgrounds: the left-hand shade first (it paints over
     the gradient below it), then the vertical sky itself. The shade is
     on the sky rather than in a layer so parallax can never slide it
     off the story column. */
  var sky = 'linear-gradient(90deg,rgba(' + k + ',.86) 0%,rgba(' + k + ',.70) 22%,rgba(' + k + ',.34) 40%,rgba(' + k + ',0) 58%),' +
    'linear-gradient(180deg,' + SCENES[key].sky.join(',') + ')';
  return '<div class="sky" style="background:' + sky + '"></div>\n' +
    layerHTML('far', '.28', L.far) + '\n' + layerHTML('mid', '.55', L.mid) + '\n' + layerHTML('near', '1', L.near);
}

root.SCENES = SCENES;
root.sceneHTML = sceneHTML;

})(typeof window !== 'undefined' ? window : this);
